import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, { [key: string]: string }> = {
  en: {
    // Header
    'header.title': 'RetailPOS',
    'header.subtitle': 'Point of Sale System',
    'header.reports': 'Reports',
    'header.settings': 'Settings',
    'header.cashier': 'John Doe',
    
    // Search and Barcode
    'search.barcode.placeholder': 'Scan or enter barcode...',
    'search.barcode.ready': 'Barcode Ready',
    'search.barcode.help': '💡 Scan barcode or type SKU and press Enter',
    'search.product.placeholder': 'Search by product',
    'search.category.all': 'all',
    
    // Categories
    'category.beverages': 'beverages',
    'category.bakery': 'bakery',
    'category.electronics': 'electronics',
    'category.produce': 'produce',
    'category.stationery': 'stationery',
    'category.clothing': 'clothing',
   'category.snacks': 'snacks',
   'category.health & beauty': 'health & beauty',
    
    // Cart
    'cart.title': 'Cart',
    'cart.items': 'items',
    'cart.empty.title': 'Cart is empty',
    'cart.empty.subtitle': 'Add products to start a transaction',
    'cart.items.in.cart': 'Items in cart',
    'cart.subtotal': 'Subtotal:',
    'cart.tax': 'Tax (8%):',
    'cart.total': 'Total:',
    'cart.select.customer': 'Select Customer',
    'cart.cash.payment': 'Cash Payment',
    'cart.low.stock': 'Low Stock',
    
    // Payment Modal
    'payment.title': 'Cash Payment',
    'payment.total.amount': 'Total Amount',
    'payment.cash.received': 'Cash Received',
    'payment.enter.amount': 'Enter amount received',
    'payment.change': 'Change:',
    'payment.processing': 'Processing payment...',
    'payment.cancel': 'Cancel',
    'payment.complete': 'Complete Payment',
    'payment.processing.button': 'Processing...',
    
    // Customer Modal
    'customer.title': 'Select Customer',
    'customer.search': 'Search customers...',
    'customer.walk.in': 'Walk-in Customer',
    'customer.walk.in.desc': 'No customer information',
    'customer.points': 'points',
    'customer.add.new': 'Add New Customer',
    'customer.add.title': 'Add New Customer',
    'customer.name': 'Full Name',
    'customer.name.required': 'Full Name *',
    'customer.email': 'Email Address',
    'customer.email.required': 'Email Address *',
    'customer.phone': 'Phone Number',
    'customer.name.placeholder': 'Enter customer name',
    'customer.email.placeholder': 'Enter email address',
    'customer.phone.placeholder': 'Enter phone number',
    'customer.cancel': 'Cancel',
    'customer.add': 'Add Customer',
    
    // Receipt Modal
    'receipt.title': 'Transaction Complete',
    'receipt.store.name': 'RetailPOS Store',
    'receipt.store.address': '123 Main Street, City, State 12345',
    'receipt.store.phone': 'Phone: (555) 123-4567',
    'receipt.transaction.id': 'Transaction ID:',
    'receipt.date.time': 'Date & Time:',
    'receipt.cashier': 'Cashier:',
    'receipt.customer': 'Customer:',
    'receipt.items.purchased': 'Items Purchased',
    'receipt.subtotal': 'Subtotal:',
    'receipt.tax': 'Tax (8%):',
    'receipt.total': 'Total:',
    'receipt.payment.method': 'Payment Method:',
    'receipt.amount.paid': 'Amount Paid:',
    'receipt.change': 'Change:',
    'receipt.thank.you': 'Thank you for your business!',
    'receipt.keep.receipt': 'Please keep this receipt for your records',
    'receipt.loyalty.points': 'Loyalty Points Earned:',
    'receipt.print': 'Print',
    'receipt.email': 'Email',
    'receipt.download': 'Download',
    'receipt.new.transaction': 'New Transaction',
    
    // Product Grid
    'product.each': 'each',
    
    // Notifications
    'notification.added': 'Added',
    'notification.to.cart': 'to cart',
    'notification.not.found': 'Product not found:',
    
    // Payment Methods
    'payment.method.cash': 'cash',
    
    // Sidebar
    'sidebar.reports': 'Reports',
    'sidebar.orders': 'Orders',
    'sidebar.categories': 'Categories',
    'sidebar.users': 'Users',
    'sidebar.profile': 'Profile',
    'sidebar.suppliers': 'Suppliers',
    'sidebar.inventory': 'Inventory',
    'sidebar.customers': 'Customers',
    'sidebar.transactions': 'Transactions',
    'sidebar.settings': 'Settings',
    'sidebar.logout': 'Logout',
    'sidebar.cashier.role': 'Cashier',
    'sidebar.logout.confirm.title': 'Confirm Logout',
    'sidebar.logout.confirm.message': 'Are you sure you want to logout? You will need to sign in again to access the system.',
    'sidebar.logout.cancel': 'Cancel',
    'sidebar.logout.confirm.button': 'Logout',
    'sidebar.logout.success': 'Logged out successfully!',
    'sidebar.reports.coming.soon': 'Reports coming soon...',
    'sidebar.profile.coming.soon': 'Profile management coming soon...',
    'sidebar.inventory.coming.soon': 'Inventory management coming soon...',
    'sidebar.customers.coming.soon': 'Customer management coming soon...',
    'sidebar.transactions.coming.soon': 'Transaction history coming soon...',
    'sidebar.settings.coming.soon': 'Settings coming soon...',

    // Reports Page
    'reports.title': 'Reports & Analytics',
    'reports.overview': 'Overview',
    'reports.sales': 'Sales Report',
    'reports.inventory': 'Inventory Report',
    'reports.customers': 'Customer Report',
    'reports.products': 'Product Report',
    'reports.date.today': 'Today',
    'reports.date.yesterday': 'Yesterday',
    'reports.date.week': 'This Week',
    'reports.date.month': 'This Month',
    'reports.date.quarter': 'This Quarter',
    'reports.date.year': 'This Year',
    'reports.date.custom': 'Custom Range',
    'reports.export.print': 'Print',
    'reports.export.pdf': 'PDF',
    'reports.export.excel': 'Excel',
    'reports.export.csv': 'CSV',
    'reports.metrics.total.sales': 'Total Sales',
    'reports.metrics.transactions': 'Transactions',
    'reports.metrics.customers': 'Customers',
    'reports.metrics.avg.transaction': 'Avg Transaction',
    'reports.trend.up': 'up',
    'reports.trend.down': 'down',
    'reports.chart.daily.sales': 'Daily Sales Trend',
    'reports.chart.top.products': 'Top Products',
    'reports.chart.category.sales': 'Sales by Category',
    'reports.table.date': 'Date',
    'reports.table.sales': 'Sales',
    'reports.table.transactions': 'Transactions',
    'reports.table.customers': 'Customers',
    'reports.table.avg.transaction': 'Avg Transaction',
    'reports.inventory.total.items': 'Total Items',
    'reports.inventory.low.stock': 'Low Stock',
    'reports.inventory.out.of.stock': 'Out of Stock',
    'reports.product.sold': 'sold',
    'reports.export.success': 'Report exported successfully!',

    // Profile Page
    'profile.title': 'Profile Management',
    'profile.personal.info': 'Personal Information',
    'profile.edit': 'Edit Profile',
    'profile.save': 'Save Changes',
    'profile.cancel': 'Cancel',
    'profile.full.name': 'Full Name',
    'profile.employee.id': 'Employee ID',
    'profile.email': 'Email Address',
    'profile.phone': 'Phone Number',
    'profile.address': 'Address',
    'profile.work.info': 'Work Information',
    'profile.role': 'Role',
    'profile.department': 'Department',
    'profile.join.date': 'Join Date',
    'profile.performance': 'Performance Overview',
    'profile.stats.total.sales': 'Total Sales',
    'profile.stats.transactions': 'Transactions',
    'profile.stats.days.active': 'Days Active',
    'profile.stats.last.login': 'Last Login',

    // Orders Page
    'orders.title': 'Orders Management',
    'orders.stats.total': 'Total Orders',
    'orders.stats.completed': 'Completed',
    'orders.stats.pending': 'Pending',
    'orders.stats.revenue': 'Revenue',
    'orders.search.placeholder': 'Search orders...',
    'orders.filter.all': 'All Status',
    'orders.filter.completed': 'Completed',
    'orders.filter.pending': 'Pending',
    'orders.filter.cancelled': 'Cancelled',
    'orders.table.order': 'Order',
    'orders.table.customer': 'Customer',
    'orders.table.items': 'Items',
    'orders.table.total': 'Total',
    'orders.table.status': 'Status',
    'orders.table.date': 'Date',
    'orders.table.actions': 'Actions',
    'orders.table.items.count': 'items',
    'orders.status.completed': 'completed',
    'orders.status.pending': 'pending',
    'orders.status.cancelled': 'cancelled',
    'orders.actions.view': 'View Details',
    'orders.actions.print': 'Print Order',
    'orders.actions.print.success': 'Order printed successfully!',
    'orders.empty.title': 'No orders found',
    'orders.empty.subtitle': 'Orders will appear here when customers make purchases',
    'orders.detail.title': 'Order Details',
    'orders.detail.order.id': 'Order ID',
    'orders.detail.status': 'Status',
    'orders.detail.customer': 'Customer',
    'orders.detail.date': 'Date & Time',
    'orders.detail.items': 'Order Items',
    'orders.detail.total': 'Total Amount',
    'orders.detail.payment.method': 'Payment Method',
    'orders.detail.close': 'Close',

    // Inventory Page
    'inventory.title': 'Inventory Management',
    'inventory.stats.total.items': 'Total Items',
    'inventory.stats.low.stock': 'Low Stock',
    'inventory.stats.out.of.stock': 'Out of Stock',
    'inventory.stats.total.value': 'Total Value',
    'inventory.search.placeholder': 'Search inventory...',
    'inventory.filter.all.categories': 'All Categories',
    'inventory.filter.all.stock': 'All Stock Levels',
    'inventory.filter.in.stock': 'In Stock',
    'inventory.filter.low.stock': 'Low Stock',
    'inventory.filter.out.of.stock': 'Out of Stock',
    'inventory.add.item': 'Add Item',
    'inventory.table.product': 'Product',
    'inventory.table.sku': 'SKU',
    'inventory.table.category': 'Category',
    'inventory.table.stock': 'Stock',
    'inventory.table.price': 'Price',
    'inventory.table.supplier': 'Supplier',
    'inventory.table.actions': 'Actions',
    'inventory.last.restocked': 'Last restocked',
    'inventory.actions.edit': 'Edit Item',
    'inventory.actions.delete': 'Delete Item',
    'inventory.delete.confirm': 'Are you sure you want to delete this item?',
    'inventory.empty.title': 'No inventory items found',
    'inventory.empty.subtitle': 'Add items to start managing your inventory',
    'inventory.add.title': 'Add New Item',
    'inventory.edit.title': 'Edit Item',
    'inventory.view.title': 'View Item',
    'inventory.actions.view': 'View Item',
    'inventory.form.name': 'Product Name',
    'inventory.form.name.placeholder': 'Enter product name',
    'inventory.form.sku': 'SKU',
    'inventory.form.sku.placeholder': 'Enter SKU/Barcode',
    'inventory.form.category': 'Category',
    'inventory.form.supplier': 'Supplier',
    'inventory.form.supplier.placeholder': 'Enter supplier name',
    'inventory.form.cost.price': 'Cost Price',
    'inventory.form.selling.price': 'Selling Price',
    'inventory.form.stock': 'Stock Quantity',
    'inventory.form.reorder.level': 'Reorder Level',
    'inventory.form.description': 'Description',
    'inventory.form.description.placeholder': 'Enter product description',
    'inventory.form.cancel': 'Cancel',
    'inventory.form.add': 'Add Item',
    'inventory.form.save': 'Save Changes',
    'inventory.form.select.category': 'Select Category',
    'inventory.form.select.supplier': 'Select Supplier',
    'inventory.form.adding': 'Adding Item...',
    'inventory.form.saving': 'Saving...',
    'inventory.info.supplier': 'Supplier',
    'inventory.info.last.restocked': 'Last Restocked',
    'inventory.info.created': 'Created',
    'loading.inventory': 'Loading inventory...',

    // Settings Page
    'settings.title': 'System Settings',
    'settings.tabs.store': 'Store',
    'settings.tabs.system': 'System',
    'settings.tabs.receipt': 'Receipt',
    'settings.tabs.notifications': 'Notifications',
    'settings.tabs.security': 'Security',
    'settings.tabs.display': 'Display',
    'settings.store.info': 'Store Information',
    'settings.store.name': 'Store Name',
    'settings.store.phone': 'Phone Number',
    'settings.store.address': 'Address',
    'settings.store.email': 'Email Address',
    'settings.tax.settings': 'Tax Settings',
    'settings.tax.rate': 'Tax Rate',
    'settings.tax.included': 'Tax included in prices',
    'settings.system.general': 'General Settings',
    'settings.system.currency': 'Currency',
    'settings.system.date.format': 'Date Format',
    'settings.system.time.format': 'Time Format',
    'settings.system.time.12': '12 Hour',
    'settings.system.time.24': '24 Hour',
    'settings.system.low.stock.threshold': 'Low Stock Threshold',
    'settings.receipt.customization': 'Receipt Customization',
    'settings.receipt.header': 'Receipt Header',
    'settings.receipt.footer': 'Receipt Footer',
    'settings.receipt.printing': 'Printing Settings',
    'settings.receipt.print.logo': 'Print Logo',
    'settings.receipt.auto.print': 'Auto Print',
    'settings.notifications.alerts': 'Alert Settings',
    'settings.notifications.low.stock': 'Low Stock Alerts',
    'settings.notifications.email': 'Email Notifications',
    'settings.notifications.sound': 'Sound Effects',
    'settings.security.access': 'Access Control',
    'settings.security.session.timeout': 'Session Timeout',
    'settings.security.minutes': 'minutes',
    'settings.security.password.change': 'Require Password Change',
    'settings.security.two.factor': 'Two-Factor Authentication',
    'settings.display.appearance': 'Appearance',
    'settings.display.theme': 'Theme',
    'settings.display.theme.light': 'Light',
    'settings.display.theme.dark': 'Dark',
    'settings.display.theme.auto': 'Auto',
    'settings.display.compact.mode': 'Compact Mode',
    'settings.display.product.images': 'Show Product Images',
    'settings.saved.successfully': 'Settings saved successfully',
    'settings.unsaved.changes': 'You have unsaved changes',
    'settings.reset.defaults': 'Reset to Defaults',
    'settings.save.changes': 'Save Changes',
    'settings.reset.confirm': 'Are you sure you want to reset all settings to default values?'
    ,

    // Authentication
    'auth.login.title': 'Sign in to your account',
    'auth.signup.title': 'Create your account',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.confirm.password': 'Confirm Password',
    'auth.full.name': 'Full Name',
    'auth.employee.id': 'Employee ID',
    'auth.role': 'Role',
    'auth.role.admin': 'Admin',
    'auth.role.manager': 'Manager',
    'auth.role.cashier': 'Cashier',
    'auth.login.button': 'Sign In',
    'auth.signup.button': 'Create Account',
    'auth.login.link': 'Sign in here',
    'auth.signup.link': 'Sign up here',
    'auth.no.account': "Don't have an account?",
    'auth.have.account': 'Already have an account?',
    'auth.demo.credentials': 'Demo Credentials',
    'auth.use.button': 'Use',
    'auth.signing.in': 'Signing in...',
    'auth.creating.account': 'Creating account...',
    'auth.loading': 'Loading...',
    'auth.error.passwords.match': 'Passwords do not match',
    'auth.error.password.length': 'Password must be at least 6 characters long',
    'auth.placeholder.email': 'Enter your email',
    'auth.placeholder.password': 'Enter your password',
    'auth.placeholder.confirm.password': 'Confirm your password',
    'auth.placeholder.full.name': 'Enter your full name',
    'auth.placeholder.employee.id': 'Enter employee ID',

    // Categories Page
    'categories.title': 'Category Management',
    'categories.stats.total': 'Total Categories',
    'categories.stats.products': 'Total Products',
    'categories.stats.average': 'Avg per Category',
    'categories.search.placeholder': 'Search categories...',
    'categories.add.category': 'Add Category',
    'categories.products': 'products',
    'categories.updated': 'Updated',
    'categories.actions.edit': 'Edit Category',
    'categories.actions.delete': 'Delete Category',
    'categories.actions.view': 'View Category',
    'categories.delete.confirm': 'Are you sure you want to delete this category?',
    'categories.empty.title': 'No categories found',
    'categories.empty.subtitle': 'Add categories to organize your products',
    'categories.add.title': 'Add New Category',
    'categories.edit.title': 'Edit Category',
    'categories.view.title': 'View Category',
    'categories.form.name': 'Category Name',
    'categories.form.name.placeholder': 'Enter category name',
    'categories.form.description': 'Description',
    'categories.form.description.placeholder': 'Enter category description',
    'categories.form.color': 'Color',
    'categories.form.cancel': 'Cancel',
    'categories.form.add': 'Add Category',
    'categories.form.save': 'Save Changes',
    'categories.form.adding': 'Adding Category...',
    'categories.form.saving': 'Saving...',
    'categories.info.products': 'Products',
    'categories.info.created': 'Created',
    'categories.info.updated': 'Updated',
    'loading.categories': 'Loading categories...',

    // Suppliers Page
    'suppliers.title': 'Supplier Management',
    'suppliers.stats.total': 'Total Suppliers',
    'suppliers.stats.active': 'Active',
    'suppliers.stats.products': 'Total Products',
    'suppliers.stats.average': 'Avg per Supplier',
    'suppliers.search.placeholder': 'Search suppliers...',
    'suppliers.filter.all.status': 'All Status',
    'suppliers.status.active': 'Active',
    'suppliers.status.inactive': 'Inactive',
    'suppliers.add.supplier': 'Add Supplier',
    'suppliers.table.supplier': 'Supplier',
    'suppliers.table.contact': 'Contact',
    'suppliers.table.location': 'Location',
    'suppliers.table.products': 'Products',
    'suppliers.table.status': 'Status',
    'suppliers.table.actions': 'Actions',
    'suppliers.products.supplied': 'products supplied',
    'suppliers.actions.edit': 'Edit Supplier',
    'suppliers.actions.delete': 'Delete Supplier',
    'suppliers.actions.view': 'View Supplier',
    'suppliers.delete.confirm': 'Are you sure you want to delete this supplier?',
    'suppliers.empty.title': 'No suppliers found',
    'suppliers.empty.subtitle': 'Add suppliers to manage your supply chain',
    'suppliers.add.title': 'Add New Supplier',
    'suppliers.edit.title': 'Edit Supplier',
    'suppliers.view.title': 'View Supplier',
    'suppliers.form.name': 'Supplier Name',
    'suppliers.form.name.placeholder': 'Enter supplier name',
    'suppliers.form.contact.person': 'Contact Person',
    'suppliers.form.contact.person.placeholder': 'Enter contact person name',
    'suppliers.form.email': 'Email Address',
    'suppliers.form.email.placeholder': 'Enter email address',
    'suppliers.form.phone': 'Phone Number',
    'suppliers.form.phone.placeholder': 'Enter phone number',
    'suppliers.form.address': 'Address',
    'suppliers.form.address.placeholder': 'Enter full address',
    'suppliers.form.city': 'City',
    'suppliers.form.city.placeholder': 'Enter city',
    'suppliers.form.country': 'Country',
    'suppliers.form.country.placeholder': 'Enter country',
    'suppliers.form.payment.terms': 'Payment Terms',
    'suppliers.form.state': 'State',
    'suppliers.form.state.placeholder': 'Enter state',
    'suppliers.form.zip.code': 'Zip Code',
    'suppliers.form.zip.code.placeholder': 'Enter zip code',
    'suppliers.form.status': 'Status',
    'suppliers.form.cancel': 'Cancel',

    // Sidebar
    'sidebar.dashboard': 'Dashboard',
    'sidebar.employees': 'Employees',
    'sidebar.clients': 'Clients',
    'sidebar.inventory': 'Inventory',
    'sidebar.orders': 'Orders',
    'sidebar.categories': 'Categories',
    'sidebar.suppliers': 'Suppliers',
    'sidebar.users': 'Users',
    'sidebar.reports': 'Reports',
    'sidebar.profile': 'Profile',
    'sidebar.settings': 'Settings',
    'sidebar.logout': 'Logout',
    'sidebar.cashier.role': 'Cashier',
    'sidebar.logout.confirm.title': 'Confirm Logout',
    'sidebar.logout.confirm.message': 'Are you sure you want to logout?',
    'sidebar.logout.cancel': 'Cancel',
    'sidebar.logout.confirm.button': 'Logout',
    'suppliers.form.add': 'Add Supplier',
    'suppliers.form.save': 'Save Changes',
    'suppliers.form.adding': 'Adding Supplier...',
    'suppliers.form.saving': 'Saving...',
    'suppliers.info.products.supplied': 'Products Supplied',
    'suppliers.info.created': 'Created',
    'suppliers.info.updated': 'Updated',

    // Users Page
    'suppliers.delete.confirm': 'Are you sure you want to delete this supplier?',
    'users.stats.total': 'Total Users',
    'users.stats.active': 'Active',
    'users.stats.admins': 'Admins',
    'users.stats.managers': 'Managers',
    'users.search.placeholder': 'Search users...',
    'users.filter.all.roles': 'All Roles',
    'users.filter.all.status': 'All Status',
    'users.status.active': 'Active',
    'users.status.inactive': 'Inactive',
    'users.add.user': 'Add User',
    'users.table.user': 'User',
    'users.table.contact': 'Contact',
    'users.table.role': 'Role',
    'users.table.status': 'Status',
    'users.table.last.login': 'Last Login',
    'users.table.actions': 'Actions',
    'users.actions.edit': 'Edit User',
    'users.actions.delete': 'Delete User',
    'users.actions.view': 'View User',
    'users.delete.confirm': 'Are you sure you want to delete this user?',
    'users.empty.title': 'No users found',
    'users.empty.subtitle': 'Add users to manage your team',
    'users.add.title': 'Add New User',
    'users.edit.title': 'Edit User',
    'users.view.title': 'View User',
    'users.form.name': 'Full Name',
    'users.form.name.placeholder': 'Enter full name',
    'users.form.email': 'Email Address',
    'users.form.email.placeholder': 'Enter email address',
    'users.form.phone': 'Phone Number',
    'users.form.phone.placeholder': 'Enter phone number',
    'users.form.employee.id': 'Employee ID',
    'users.form.employee.id.placeholder': 'Enter employee ID',
    'users.form.role': 'Role',
    'users.form.status': 'Status',
    'users.form.cancel': 'Cancel',
    'users.form.add': 'Add User',
    'users.form.save': 'Save Changes',
    'users.info.last.login': 'Last Login',
    'users.info.created': 'Created',
    'users.info.updated': 'Updated',
    'users.access.denied.title': 'Access Denied',
    'users.access.denied.message': 'You do not have permission to access user management',
    
    // Loading States
    'loading.suppliers': 'Loading suppliers...',
    'loading.store.data': 'Loading store data...',
    'loading.products': 'Loading products...',
    'loading.customers': 'Loading customers...',
    'loading.transactions': 'Loading transactions...',

    // Dashboard
    'dashboard.title': 'Business Dashboard',
    'dashboard.welcome': 'Welcome back! Here\'s your business overview for today',
    'dashboard.last.updated': 'Last updated',
    'dashboard.stats.today.sales': 'Today\'s Sales',
    'dashboard.stats.active.employees': 'Active Employees',
    'dashboard.stats.low.stock': 'Low Stock Items',
    'dashboard.stats.orders.today': 'Orders Today',
    'dashboard.recent.sales': 'Recent Sales',
    'dashboard.alerts.notifications': 'Alerts & Notifications',
    'dashboard.current.shift': 'Current Shift',
    'dashboard.quick.actions': 'Quick Actions',
    'dashboard.new.sale': 'New Sale',
    'dashboard.add.inventory': 'Add Inventory',
    'dashboard.schedule.staff': 'Schedule Staff',
    'dashboard.view.reports': 'View Reports',
    'dashboard.view.all.notifications': 'View All Notifications',
    'dashboard.on.duty': 'On Duty',
    'dashboard.starts.at': 'Starts at',
    'dashboard.items': 'items',

    // Clients
    'clients.title': 'Clients',
    'clients.subtitle': 'Manage your client relationships',
    'clients.add.client': 'Add Client',
    'clients.stats.active': 'Active Clients',
    'clients.stats.total.revenue': 'Total Revenue',
    'clients.stats.active.invoices': 'Active Invoices',
    'clients.stats.new.clients': 'New clients',
    'clients.stats.this.month': 'This Month',
    'clients.search.placeholder': 'Search clients...',
    'clients.create.invoice': 'Create Invoice',
    'clients.view.details': 'View Details',
    'clients.total.revenue': 'Total Revenue',
    'clients.projects': 'Projects',
    'clients.active.invoices': 'Active Invoices',
    'clients.last.transaction': 'Last Transaction',
    'clients.add.title': 'Add New Client',
    'clients.form.company.name': 'Company Name',
    'clients.form.company.placeholder': 'Enter company name',
    'clients.form.email': 'Email',
    'clients.form.email.placeholder': 'contact@company.com',
    'clients.form.phone': 'Phone',
    'clients.form.phone.placeholder': '+1 (555) 123-4567',
    'clients.form.address': 'Address',
    'clients.form.address.placeholder': 'Enter full address',
    'clients.form.notes': 'Notes',
    'clients.form.notes.placeholder': 'Additional notes about the client...',
    'clients.form.cancel': 'Cancel',
    'clients.form.add': 'Add Client',

    // Employees
    'employees.title': 'Employee Management',
    'employees.subtitle': 'Manage your workforce and schedules',
    'employees.add.employee': 'Add Employee',
    'employees.tab.employees': 'Employees',
    'employees.tab.schedule': 'Schedule',
    'employees.stats.total': 'Total Employees',
    'employees.stats.active.today': 'Active Today',
    'employees.stats.weekly.payroll': 'Weekly Payroll',
    'employees.stats.avg.performance': 'Avg Performance',
    'employees.search.placeholder': 'Search employees...',
    'employees.filter.all.departments': 'All Departments',
    'employees.department.management': 'Management',
    'employees.department.sales': 'Sales',
    'employees.department.inventory': 'Inventory',
    'employees.department.pharmacy': 'Pharmacy',
    'employees.department.security': 'Security',
    'employees.hourly.rate': 'Hourly Rate',
    'employees.this.week': 'This Week',
    'employees.department': 'Department',
    'employees.performance': 'Performance',
    'employees.edit.details': 'Edit Details',
    'employees.view.schedule': 'View Schedule',
    'employees.weekly.schedule': 'Weekly Schedule',
    'employees.employee': 'Employee',
    'employees.monday': 'Monday',
    'employees.tuesday': 'Tuesday',
    'employees.wednesday': 'Wednesday',
    'employees.thursday': 'Thursday',
    'employees.friday': 'Friday',
    'employees.saturday': 'Saturday',
    'employees.sunday': 'Sunday',
    'employees.off': 'Off',
    'employees.add.title': 'Add New Employee',
    'employees.form.full.name': 'Full Name',
    'employees.form.full.name.placeholder': 'Enter full name',
    'employees.form.position': 'Position',
    'employees.form.position.placeholder': 'Job position',
    'employees.form.department': 'Department',
    'employees.form.hourly.rate': 'Hourly Rate',
    'employees.form.hourly.rate.placeholder': '0.00',
    'employees.form.email': 'Email',
    'employees.form.email.placeholder': 'employee@store.com',
    'employees.form.phone': 'Phone',
    'employees.form.phone.placeholder': '+1 (555) 123-4567',
    'employees.form.hire.date': 'Hire Date',
    'employees.form.shift': 'Shift',
    'employees.form.shift.placeholder': '9:00 AM - 5:00 PM',
    'employees.form.cancel': 'Cancel',
    'employees.form.add': 'Add Employee'
  },
  ar: {
    // Header
    'header.title': 'نقاط البيع',
    'header.subtitle': 'نظام نقاط البيع',
    'header.reports': 'التقارير',
    'header.settings': 'الإعدادات',
    'header.cashier': 'جون دو',
    
    // Search and Barcode
    'search.barcode.placeholder': 'امسح أو أدخل الباركود...',
    'search.barcode.ready': 'الباركود جاهز',
    'search.barcode.help': '💡 امسح الباركود أو اكتب رمز المنتج واضغط Enter',
    'search.product.placeholder': 'البحث عن منتج',
    'search.category.all': 'الكل',
    
    // Categories
    'category.beverages': 'المشروبات',
    'category.bakery': 'المخبوزات',
    'category.electronics': 'الإلكترونيات',
    'category.produce': 'المنتجات الطازجة',
    'category.stationery': 'القرطاسية',
    'category.clothing': 'الملابس',
   'category.snacks': 'الوجبات الخفيفة',
   'category.health & beauty': 'الصحة والجمال',
    
    // Cart
    'cart.title': 'السلة',
    'cart.items': 'عناصر',
    'cart.empty.title': 'السلة فارغة',
    'cart.empty.subtitle': 'أضف منتجات لبدء المعاملة',
    'cart.items.in.cart': 'العناصر في السلة',
    'cart.subtotal': 'المجموع الفرعي:',
    'cart.tax': 'الضريبة (8%):',
    'cart.total': 'المجموع:',
    'cart.select.customer': 'اختر العميل',
    'cart.cash.payment': 'دفع نقدي',
    'cart.low.stock': 'مخزون قليل',
    
    // Payment Modal
    'payment.title': 'دفع نقدي',
    'payment.total.amount': 'المبلغ الإجمالي',
    'payment.cash.received': 'النقد المستلم',
    'payment.enter.amount': 'أدخل المبلغ المستلم',
    'payment.change': 'الباقي:',
    'payment.processing': 'جاري معالجة الدفع...',
    'payment.cancel': 'إلغاء',
    'payment.complete': 'إتمام الدفع',
    'payment.processing.button': 'جاري المعالجة...',
    
    // Customer Modal
    'customer.title': 'اختر العميل',
    'customer.search': 'البحث عن العملاء...',
    'customer.walk.in': 'عميل عادي',
    'customer.walk.in.desc': 'لا توجد معلومات عميل',
    'customer.points': 'نقاط',
    'customer.add.new': 'إضافة عميل جديد',
    'customer.add.title': 'إضافة عميل جديد',
    'customer.name': 'الاسم الكامل',
    'customer.name.required': 'الاسم الكامل *',
    'customer.email': 'عنوان البريد الإلكتروني',
    'customer.email.required': 'عنوان البريد الإلكتروني *',
    'customer.phone': 'رقم الهاتف',
    'customer.name.placeholder': 'أدخل اسم العميل',
    'customer.email.placeholder': 'أدخل عنوان البريد الإلكتروني',
    'customer.phone.placeholder': 'أدخل رقم الهاتف',
    'customer.cancel': 'إلغاء',
    'customer.add': 'إضافة عميل',
    
    // Receipt Modal
    'receipt.title': 'تمت المعاملة',
    'receipt.store.name': 'متجر نقاط البيع',
    'receipt.store.address': '123 الشارع الرئيسي، المدينة، الولاية 12345',
    'receipt.store.phone': 'الهاتف: (555) 123-4567',
    'receipt.transaction.id': 'رقم المعاملة:',
    'receipt.date.time': 'التاريخ والوقت:',
    'receipt.cashier': 'أمين الصندوق:',
    'receipt.customer': 'العميل:',
    'receipt.items.purchased': 'العناصر المشتراة',
    'receipt.subtotal': 'المجموع الفرعي:',
    'receipt.tax': 'الضريبة (8%):',
    'receipt.total': 'المجموع:',
    'receipt.payment.method': 'طريقة الدفع:',
    'receipt.amount.paid': 'المبلغ المدفوع:',
    'receipt.change': 'الباقي:',
    'receipt.thank.you': 'شكراً لك على تعاملك معنا!',
    'receipt.keep.receipt': 'يرجى الاحتفاظ بهذا الإيصال لسجلاتك',
    'receipt.loyalty.points': 'نقاط الولاء المكتسبة:',
    'receipt.print': 'طباعة',
    'receipt.email': 'بريد إلكتروني',
    'receipt.download': 'تحميل',
    'receipt.new.transaction': 'معاملة جديدة',
    
    // Product Grid
    'product.each': 'للقطعة',
    
    // Notifications
    'notification.added': 'تمت إضافة',
    'notification.to.cart': 'إلى السلة',
    'notification.not.found': 'المنتج غير موجود:',
    
    // Payment Methods
    'payment.method.cash': 'نقدي',
    
    // Sidebar
    'sidebar.reports': 'التقارير',
    'sidebar.orders': 'الطلبات',
    'sidebar.categories': 'الفئات',
    'sidebar.users': 'المستخدمين',
    'sidebar.profile': 'الملف الشخصي',
    'sidebar.suppliers': 'الموردين',
    'sidebar.inventory': 'المخزون',
    'sidebar.customers': 'العملاء',
    'sidebar.transactions': 'المعاملات',
    'sidebar.settings': 'الإعدادات',
    'sidebar.logout': 'تسجيل الخروج',
    'sidebar.cashier.role': 'أمين الصندوق',
    'sidebar.logout.confirm.title': 'تأكيد تسجيل الخروج',
    'sidebar.logout.confirm.message': 'هل أنت متأكد من أنك تريد تسجيل الخروج؟ ستحتاج إلى تسجيل الدخول مرة أخرى للوصول إلى النظام.',
    'sidebar.logout.cancel': 'إلغاء',
    'sidebar.logout.confirm.button': 'تسجيل الخروج',
    'sidebar.logout.success': 'تم تسجيل الخروج بنجاح!',
    'sidebar.reports.coming.soon': 'التقارير قريباً...',
    'sidebar.profile.coming.soon': 'إدارة الملف الشخصي قريباً...',
    'sidebar.inventory.coming.soon': 'إدارة المخزون قريباً...',
    'sidebar.customers.coming.soon': 'إدارة العملاء قريباً...',
    'sidebar.transactions.coming.soon': 'سجل المعاملات قريباً...',
    'sidebar.settings.coming.soon': 'الإعدادات قريباً...',

    // Reports Page
    'reports.title': 'التقارير والتحليلات',
    'reports.overview': 'نظرة عامة',
    'reports.sales': 'تقرير المبيعات',
    'reports.inventory': 'تقرير المخزون',
    'reports.customers': 'تقرير العملاء',
    'reports.products': 'تقرير المنتجات',
    'reports.date.today': 'اليوم',
    'reports.date.yesterday': 'أمس',
    'reports.date.week': 'هذا الأسبوع',
    'reports.date.month': 'هذا الشهر',
    'reports.date.quarter': 'هذا الربع',
    'reports.date.year': 'هذا العام',
    'reports.date.custom': 'نطاق مخصص',
    'reports.export.print': 'طباعة',
    'reports.export.pdf': 'PDF',
    'reports.export.excel': 'Excel',
    'reports.export.csv': 'CSV',
    'reports.metrics.total.sales': 'إجمالي المبيعات',
    'reports.metrics.transactions': 'المعاملات',
    'reports.metrics.customers': 'العملاء',
    'reports.metrics.avg.transaction': 'متوسط المعاملة',
    'reports.trend.up': 'ارتفاع',
    'reports.trend.down': 'انخفاض',
    'reports.chart.daily.sales': 'اتجاه المبيعات اليومية',
    'reports.chart.top.products': 'أفضل المنتجات',
    'reports.chart.category.sales': 'المبيعات حسب الفئة',
    'reports.table.date': 'التاريخ',
    'reports.table.sales': 'المبيعات',
    'reports.table.transactions': 'المعاملات',
    'reports.table.customers': 'العملاء',
    'reports.table.avg.transaction': 'متوسط المعاملة',
    'reports.inventory.total.items': 'إجمالي العناصر',
    'reports.inventory.low.stock': 'مخزون قليل',
    'reports.inventory.out.of.stock': 'نفد المخزون',
    'reports.product.sold': 'مباع',
    'reports.export.success': 'تم تصدير التقرير بنجاح!',
    // Profile Page
    'profile.title': 'إدارة الملف الشخصي',
    'profile.personal.info': 'المعلومات الشخصية',
    'profile.edit': 'تعديل الملف الشخصي',
    'profile.save': 'حفظ التغييرات',
    'profile.cancel': 'إلغاء',
    'profile.full.name': 'الاسم الكامل',
    'profile.employee.id': 'رقم الموظف',
    'profile.email': 'عنوان البريد الإلكتروني',
    'profile.phone': 'رقم الهاتف',
    'profile.address': 'العنوان',
    'profile.work.info': 'معلومات العمل',
    'profile.role': 'المنصب',
    'profile.department': 'القسم',
    'profile.join.date': 'تاريخ الانضمام',
    'profile.performance': 'نظرة عامة على الأداء',
    'profile.stats.total.sales': 'إجمالي المبيعات',
    'profile.stats.transactions': 'المعاملات',
    'profile.stats.days.active': 'الأيام النشطة',
    'profile.stats.last.login': 'آخر تسجيل دخول',
    'profile.change.password': 'تغيير كلمة المرور',
    'profile.current.password': 'كلمة المرور الحالية',
    'profile.new.password': 'كلمة المرور الجديدة',
    'profile.confirm.password': 'تأكيد كلمة المرور الجديدة',
    'profile.current.password.placeholder': 'أدخل كلمة المرور الحالية',
    'profile.new.password.placeholder': 'أدخل كلمة المرور الجديدة',
    'profile.confirm.password.placeholder': 'أكد كلمة المرور الجديدة',
    'profile.change.password.button': 'تغيير كلمة المرور',
    'profile.changing.password': 'جاري تغيير كلمة المرور...',
    'profile.password.change.success': 'تم تغيير كلمة المرور بنجاح',
    'profile.password.requirements': 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
    'profile.update.success': 'تم تحديث الملف الشخصي بنجاح',
    'profile.saving': 'جاري الحفظ...',
    'profile.name.readonly': 'اتصل بالمدير لتغيير الاسم',
    'profile.email.readonly': 'اتصل بالمدير لتغيير البريد الإلكتروني',
    'profile.phone.placeholder': 'أدخل رقم الهاتف',
    'profile.address.placeholder': 'أدخل عنوانك',
    'profile.phone.not.set': 'غير محدد',
    'loading.profile': 'جاري تحميل الملف الشخصي...',

    // Orders Page
    'orders.title': 'إدارة الطلبات',
    'orders.stats.total': 'إجمالي الطلبات',
    'orders.stats.completed': 'مكتملة',
    'orders.stats.pending': 'معلقة',
    'orders.stats.revenue': 'الإيرادات',
    'orders.search.placeholder': 'البحث في الطلبات...',
    'orders.filter.all': 'جميع الحالات',
    'orders.filter.completed': 'مكتملة',
    'orders.filter.pending': 'معلقة',
    'orders.filter.cancelled': 'ملغية',
    'orders.table.order': 'الطلب',
    'orders.table.customer': 'العميل',
    'orders.table.items': 'العناصر',
    'orders.table.total': 'المجموع',
    'orders.table.status': 'الحالة',
    'orders.table.date': 'التاريخ',
    'orders.table.actions': 'الإجراءات',
    'orders.table.items.count': 'عناصر',
    'orders.status.completed': 'مكتملة',
    'orders.status.pending': 'معلقة',
    'orders.status.cancelled': 'ملغية',
    'orders.actions.view': 'عرض التفاصيل',
    'orders.actions.print': 'طباعة الطلب',
    'orders.actions.print.success': 'تم طباعة الطلب بنجاح!',
    'orders.empty.title': 'لا توجد طلبات',
    'orders.empty.subtitle': 'ستظهر الطلبات هنا عندما يقوم العملاء بالشراء',
    'orders.detail.title': 'تفاصيل الطلب',
    'orders.detail.order.id': 'رقم الطلب',
    'orders.detail.status': 'الحالة',
    'orders.detail.customer': 'العميل',
    'orders.detail.date': 'التاريخ والوقت',
    'orders.detail.items': 'عناصر الطلب',
    'orders.detail.total': 'المبلغ الإجمالي',
    'orders.detail.payment.method': 'طريقة الدفع',
    'orders.detail.close': 'إغلاق',

    // Inventory Page
    'inventory.title': 'إدارة المخزون',
    'inventory.stats.total.items': 'إجمالي العناصر',
    'inventory.stats.low.stock': 'مخزون قليل',
    'inventory.stats.out.of.stock': 'نفد المخزون',
    'inventory.stats.total.value': 'القيمة الإجمالية',
    'inventory.search.placeholder': 'البحث في المخزون...',
    'inventory.filter.all.categories': 'جميع الفئات',
    'inventory.filter.all.stock': 'جميع مستويات المخزون',
    'inventory.filter.in.stock': 'متوفر',
    'inventory.filter.low.stock': 'مخزون قليل',
    'inventory.filter.out.of.stock': 'نفد المخزون',
    'inventory.add.item': 'إضافة عنصر',
    'inventory.table.product': 'المنتج',
    'inventory.table.sku': 'رمز المنتج',
    'inventory.table.category': 'الفئة',
    'inventory.table.stock': 'المخزون',
    'inventory.table.price': 'السعر',
    'inventory.table.supplier': 'المورد',
    'inventory.table.actions': 'الإجراءات',
    'inventory.last.restocked': 'آخر تجديد',
    'inventory.actions.edit': 'تعديل العنصر',
    'inventory.actions.delete': 'حذف العنصر',
    'inventory.delete.confirm': 'هل أنت متأكد من أنك تريد حذف هذا العنصر؟',
    'inventory.empty.title': 'لا توجد عناصر مخزون',
    'inventory.empty.subtitle': 'أضف عناصر لبدء إدارة مخزونك',
    'inventory.add.title': 'إضافة عنصر جديد',
    'inventory.edit.title': 'تعديل العنصر',
    'inventory.view.title': 'عرض العنصر',
    'inventory.actions.view': 'عرض العنصر',
    'inventory.form.name': 'اسم المنتج',
    'inventory.form.name.placeholder': 'أدخل اسم المنتج',
    'inventory.form.sku': 'رمز المنتج',
    'inventory.form.sku.placeholder': 'أدخل رمز المنتج/الباركود',
    'inventory.form.category': 'الفئة',
    'inventory.form.supplier': 'المورد',
    'inventory.form.supplier.placeholder': 'أدخل اسم المورد',
    'inventory.form.cost.price': 'سعر التكلفة',
    'inventory.form.selling.price': 'سعر البيع',
    'inventory.form.stock': 'كمية المخزون',
    'inventory.form.reorder.level': 'مستوى إعادة الطلب',
    'inventory.form.description': 'الوصف',
    'inventory.form.description.placeholder': 'أدخل وصف المنتج',
    'inventory.form.image': 'صورة المنتج',
    'inventory.form.image.help': 'ارفع JPG أو PNG أو WebP (حد أقصى 5 ميجابايت)',
    'inventory.form.image.remove': 'إزالة الصورة',
    'inventory.form.cancel': 'إلغاء',
    'inventory.form.add': 'إضافة عنصر',
    'inventory.form.save': 'حفظ التغييرات',
    'inventory.form.select.category': 'اختر الفئة',
    'inventory.form.select.supplier': 'اختر المورد',
    'inventory.form.adding': 'جاري الإضافة...',
    'inventory.form.saving': 'جاري الحفظ...',
    'inventory.info.supplier': 'المورد',
    'inventory.info.last.restocked': 'آخر تجديد',
    'inventory.info.created': 'تم الإنشاء',
    'loading.inventory': 'جاري تحميل المخزون...',

    // Settings Page
    'settings.title': 'إعدادات النظام',
    'settings.tabs.store': 'المتجر',
    'settings.tabs.system': 'النظام',
    'settings.tabs.receipt': 'الإيصال',
    'settings.tabs.notifications': 'الإشعارات',
    'settings.tabs.security': 'الأمان',
    'settings.tabs.display': 'العرض',
    'settings.store.info': 'معلومات المتجر',
    'settings.store.name': 'اسم المتجر',
    'settings.store.phone': 'رقم الهاتف',
    'settings.store.address': 'العنوان',
    'settings.store.email': 'البريد الإلكتروني',
    'settings.tax.settings': 'إعدادات الضريبة',
    'settings.tax.rate': 'معدل الضريبة',
    'settings.tax.included': 'الضريبة مشمولة في السعر',
    'settings.system.general': 'الإعدادات العامة',
    'settings.system.currency': 'العملة',
    'settings.system.date.format': 'تنسيق التاريخ',
    'settings.system.time.format': 'تنسيق الوقت',
    'settings.system.time.12': '12 ساعة',
    'settings.system.time.24': '24 ساعة',
    'settings.system.low.stock.threshold': 'حد المخزون المنخفض',
    'settings.receipt.customization': 'تخصيص الإيصال',
    'settings.receipt.header': 'رأس الإيصال',
    'settings.receipt.footer': 'تذييل الإيصال',
    'settings.receipt.printing': 'إعدادات الطباعة',
    'settings.receipt.print.logo': 'طباعة الشعار',
    'settings.receipt.auto.print': 'طباعة تلقائية',
    'settings.notifications.alerts': 'التنبيهات',
    'settings.notifications.low.stock': 'تنبيهات المخزون المنخفض',
    'settings.notifications.email': 'إشعارات البريد الإلكتروني',
    'settings.notifications.sound': 'المؤثرات الصوتية',
    'settings.security.access': 'التحكم في الوصول',
    'settings.security.session.timeout': 'انتهاء مهلة الجلسة',
    'settings.security.minutes': 'دقائق',
    'settings.security.password.change': 'طلب تغيير كلمة المرور',
    'settings.security.two.factor': 'المصادقة الثنائية',
    'settings.display.appearance': 'المظهر',
    'settings.display.theme': 'السمة',
    'settings.display.theme.light': 'فاتح',
    'settings.display.theme.dark': 'داكن',
    'settings.display.theme.auto': 'تلقائي',
    'settings.display.compact.mode': 'الوضع المضغوط',
    'settings.display.product.images': 'عرض صور المنتجات',
    'settings.saved.successfully': 'تم حفظ الإعدادات بنجاح',
    'settings.unsaved.changes': 'يوجد تغييرات غير محفوظة',
    'settings.reset.defaults': 'إعادة تعيين الافتراضيات',
    'settings.save.changes': 'حفظ التغييرات',
    'settings.reset.confirm': 'هل أنت متأكد من أنك تريد إعادة تعيين جميع الإعدادات إلى القيم الافتراضية؟'
    ,

    // Authentication
    'auth.login.title': 'تسجيل الدخول إلى حسابك',
    'auth.signup.title': 'إنشاء حسابك',
    'auth.email': 'عنوان البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.confirm.password': 'تأكيد كلمة المرور',
    'auth.full.name': 'الاسم الكامل',
    'auth.employee.id': 'رقم الموظف',
    'auth.role': 'المنصب',
    'auth.role.admin': 'مدير',
    'auth.role.manager': 'مدير قسم',
    'auth.role.cashier': 'أمين الصندوق',
    'auth.login.button': 'تسجيل الدخول',
    'auth.signup.button': 'إنشاء حساب',
    'auth.login.link': 'تسجيل الدخول هنا',
    'auth.signup.link': 'إنشاء حساب هنا',
    'auth.no.account': 'ليس لديك حساب؟',
    'auth.have.account': 'لديك حساب بالفعل؟',
    'auth.demo.credentials': 'بيانات تجريبية',
    'auth.use.button': 'استخدام',
    'auth.signing.in': 'جاري تسجيل الدخول...',
    'auth.creating.account': 'جاري إنشاء الحساب...',
    'auth.loading': 'جاري التحميل...',
    'auth.error.passwords.match': 'كلمات المرور غير متطابقة',
    'auth.error.password.length': 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
    'auth.placeholder.email': 'أدخل بريدك الإلكتروني',
    'auth.placeholder.password': 'أدخل كلمة المرور',
    'auth.placeholder.confirm.password': 'أكد كلمة المرور',
    'auth.placeholder.full.name': 'أدخل اسمك الكامل',
    'auth.placeholder.employee.id': 'أدخل رقم الموظف',

    // Categories Page
    'categories.title': 'إدارة الفئات',
    'categories.stats.total': 'إجمالي الفئات',
    'categories.stats.products': 'إجمالي المنتجات',
    'categories.stats.average': 'المتوسط لكل فئة',
    'categories.search.placeholder': 'البحث في الفئات...',
    'categories.add.category': 'إضافة فئة',
    'categories.products': 'منتجات',
    'categories.updated': 'محدث',
    'categories.actions.edit': 'تعديل الفئة',
    'categories.actions.delete': 'حذف الفئة',
    'categories.actions.view': 'عرض الفئة',
    'categories.delete.confirm': 'هل أنت متأكد من أنك تريد حذف هذه الفئة؟',
    'categories.empty.title': 'لا توجد فئات',
    'categories.empty.subtitle': 'أضف فئات لتنظيم منتجاتك',
    'categories.add.title': 'إضافة فئة جديدة',
    'categories.edit.title': 'تعديل الفئة',
    'categories.view.title': 'عرض الفئة',
    'categories.form.name': 'اسم الفئة',
    'categories.form.name.placeholder': 'أدخل اسم الفئة',
    'categories.form.description': 'الوصف',
    'categories.form.description.placeholder': 'أدخل وصف الفئة',
    'categories.form.color': 'اللون',
    'categories.form.cancel': 'إلغاء',
    'categories.form.add': 'إضافة فئة',
    'categories.form.save': 'حفظ التغييرات',
    'categories.form.adding': 'جاري الإضافة...',
    'categories.form.saving': 'جاري الحفظ...',
    'categories.info.products': 'المنتجات',
    'categories.info.created': 'تم الإنشاء',
    'categories.info.updated': 'تم التحديث',
    'loading.categories': 'جاري تحميل الفئات...',

    // Suppliers Page
    'suppliers.title': 'إدارة الموردين',
    'suppliers.stats.total': 'إجمالي الموردين',
    'suppliers.stats.active': 'نشط',
    'suppliers.stats.products': 'إجمالي المنتجات',
    'suppliers.stats.average': 'المتوسط لكل مورد',
    'suppliers.search.placeholder': 'البحث في الموردين...',
    'suppliers.filter.all.status': 'جميع الحالات',
    'suppliers.status.active': 'نشط',
    'suppliers.status.inactive': 'غير نشط',
    'suppliers.add.supplier': 'إضافة مورد',
    'suppliers.table.supplier': 'المورد',
    'suppliers.table.contact': 'معلومات الاتصال',
    'suppliers.table.location': 'الموقع',
    'suppliers.table.products': 'المنتجات',
    'suppliers.table.status': 'الحالة',
    'suppliers.table.actions': 'الإجراءات',
    'suppliers.products.supplied': 'منتجات موردة',
    'suppliers.actions.edit': 'تعديل المورد',
    'suppliers.actions.delete': 'حذف المورد',
    'suppliers.actions.view': 'عرض المورد',
    'suppliers.delete.confirm': 'هل أنت متأكد من أنك تريد حذف هذا المورد؟',
    'suppliers.empty.title': 'لا يوجد موردين',
    'suppliers.empty.subtitle': 'أضف موردين لإدارة سلسلة التوريد',
    'suppliers.add.title': 'إضافة مورد جديد',
    'suppliers.edit.title': 'تعديل المورد',
    'suppliers.view.title': 'عرض المورد',
    'suppliers.form.name': 'اسم المورد',
    'suppliers.form.name.placeholder': 'أدخل اسم المورد',
    'suppliers.form.contact.person': 'الشخص المسؤول',
    'suppliers.form.contact.person.placeholder': 'أدخل اسم الشخص المسؤول',
    'suppliers.form.email': 'البريد الإلكتروني',
    'suppliers.form.email.placeholder': 'أدخل البريد الإلكتروني',
    'suppliers.form.phone': 'رقم الهاتف',
    'suppliers.form.phone.placeholder': 'أدخل رقم الهاتف',
    'suppliers.form.address': 'العنوان',
    'suppliers.form.address.placeholder': 'أدخل العنوان الكامل',
    'suppliers.form.city': 'المدينة',
    'suppliers.form.city.placeholder': 'أدخل المدينة',
    'suppliers.form.country': 'البلد',
    'suppliers.form.country.placeholder': 'أدخل البلد',
    'suppliers.form.payment.terms': 'شروط الدفع',
    'suppliers.form.state': 'الولاية',
    'suppliers.form.state.placeholder': 'أدخل الولاية',
    'suppliers.form.zip.code': 'الرمز البريدي',
    'suppliers.form.zip.code.placeholder': 'أدخل الرمز البريدي',
    'suppliers.form.status': 'الحالة',
    'suppliers.form.cancel': 'إلغاء',
    'suppliers.form.add': 'إضافة مورد',
    'suppliers.form.save': 'حفظ التغييرات',
    'suppliers.form.adding': 'جاري الإضافة...',
    'suppliers.form.saving': 'جاري الحفظ...',
    'suppliers.info.products.supplied': 'المنتجات الموردة',
    'suppliers.info.created': 'تم الإنشاء',
    'suppliers.info.updated': 'تم التحديث',

    // Users Page
    'users.title': 'إدارة المستخدمين',
    'users.stats.total': 'إجمالي المستخدمين',
    'users.stats.active': 'نشط',
    'users.stats.admins': 'المديرين',
    'users.stats.managers': 'مديري الأقسام',
    'users.search.placeholder': 'البحث في المستخدمين...',
    'users.filter.all.roles': 'جميع الأدوار',
    'users.filter.all.status': 'جميع الحالات',
    'users.status.active': 'نشط',
    'users.status.inactive': 'غير نشط',
    'users.add.user': 'إضافة مستخدم',
    'users.table.user': 'المستخدم',
    'users.table.contact': 'معلومات الاتصال',
    'users.table.role': 'الدور',
    'users.table.status': 'الحالة',
    'users.table.last.login': 'آخر تسجيل دخول',
    'users.table.actions': 'الإجراءات',
    'users.actions.edit': 'تعديل المستخدم',
    'users.actions.delete': 'حذف المستخدم',
    'users.actions.view': 'عرض المستخدم',
    'users.delete.confirm': 'هل أنت متأكد من أنك تريد حذف هذا المستخدم؟',
    'users.empty.title': 'لا يوجد مستخدمين',
    'users.empty.subtitle': 'أضف مستخدمين لإدارة فريق العمل',
    'users.add.title': 'إضافة مستخدم جديد',
    'users.edit.title': 'تعديل المستخدم',
    'users.view.title': 'عرض المستخدم',
    'users.form.name': 'الاسم الكامل',
    'users.form.name.placeholder': 'أدخل الاسم الكامل',
    'users.form.email': 'البريد الإلكتروني',
    'users.form.email.placeholder': 'أدخل البريد الإلكتروني',
    'users.form.phone': 'رقم الهاتف',
    'users.form.phone.placeholder': 'أدخل رقم الهاتف',
    'users.form.employee.id': 'رقم الموظف',
    'users.form.employee.id.placeholder': 'أدخل رقم الموظف',
    'users.form.role': 'الدور',
    'users.form.password': 'كلمة المرور',
    'users.form.password.placeholder': 'أدخل كلمة المرور (6 أحرف على الأقل)',
    'users.form.status': 'الحالة',
    'users.form.cancel': 'إلغاء',
    'users.form.add': 'إضافة مستخدم',
    'users.form.adding': 'جاري الإضافة...',
    'users.form.save': 'حفظ التغييرات',
    'users.form.saving': 'جاري الحفظ...',
    'users.info.last.login': 'آخر تسجيل دخول',
    'users.info.created': 'تم الإنشاء',
    'users.info.updated': 'تم التحديث',
    'users.access.denied.title': 'الوصول مرفوض',
    'users.access.denied.message': 'ليس لديك صلاحية للوصول إلى إدارة المستخدمين',
    
    // Loading States
    'loading.suppliers': 'جاري تحميل الموردين...',
    'loading.users': 'جاري تحميل المستخدمين...',
    'loading.store.data': 'جاري تحميل بيانات المتجر...',
    'loading.products': 'جاري تحميل المنتجات...',
    'loading.customers': 'جاري تحميل العملاء...',
    'loading.transactions': 'جاري تحميل المعاملات...',

    // Dashboard
    'dashboard.title': 'لوحة تحكم الأعمال',
    'dashboard.welcome': 'مرحباً بك! إليك نظرة عامة على أعمالك لليوم',
    'dashboard.last.updated': 'آخر تحديث',
    'dashboard.stats.today.sales': 'مبيعات اليوم',
    'dashboard.stats.active.employees': 'الموظفون النشطون',
    'dashboard.stats.low.stock': 'عناصر المخزون المنخفض',
    'dashboard.stats.orders.today': 'طلبات اليوم',
    'dashboard.recent.sales': 'المبيعات الأخيرة',
    'dashboard.alerts.notifications': 'التنبيهات والإشعارات',
    'dashboard.current.shift': 'الوردية الحالية',
    'dashboard.quick.actions': 'الإجراءات السريعة',
    'dashboard.new.sale': 'بيع جديد',
    'dashboard.add.inventory': 'إضافة مخزون',
    'dashboard.schedule.staff': 'جدولة الموظفين',
    'dashboard.view.reports': 'عرض التقارير',
    'dashboard.view.all.notifications': 'عرض جميع الإشعارات',
    'dashboard.on.duty': 'في الخدمة',
    'dashboard.starts.at': 'يبدأ في',
    'dashboard.items': 'عناصر',

    // Clients
    'clients.title': 'العملاء',
    'clients.subtitle': 'إدارة علاقاتك مع العملاء',
    'clients.add.client': 'إضافة عميل',
    'clients.stats.active': 'العملاء النشطون',
    'clients.stats.total.revenue': 'إجمالي الإيرادات',
    'clients.stats.active.invoices': 'الفواتير النشطة',
    'clients.stats.new.clients': 'عملاء جدد',
    'clients.stats.this.month': 'هذا الشهر',
    'clients.search.placeholder': 'البحث في العملاء...',
    'clients.create.invoice': 'إنشاء فاتورة',
    'clients.view.details': 'عرض التفاصيل',
    'clients.total.revenue': 'إجمالي الإيرادات',
    'clients.projects': 'المشاريع',
    'clients.active.invoices': 'الفواتير النشطة',
    'clients.last.transaction': 'آخر معاملة',
    'clients.add.title': 'إضافة عميل جديد',
    'clients.form.company.name': 'اسم الشركة',
    'clients.form.company.placeholder': 'أدخل اسم الشركة',
    'clients.form.email': 'البريد الإلكتروني',
    'clients.form.email.placeholder': 'contact@company.com',
    'clients.form.phone': 'الهاتف',
    'clients.form.phone.placeholder': '+1 (555) 123-4567',
    'clients.form.address': 'العنوان',
    'clients.form.address.placeholder': 'أدخل العنوان الكامل',
    'clients.form.notes': 'ملاحظات',
    'clients.form.notes.placeholder': 'ملاحظات إضافية حول العميل...',
    'clients.form.cancel': 'إلغاء',
    'clients.form.add': 'إضافة عميل',

    // Employees
    'employees.title': 'إدارة الموظفين',
    'employees.subtitle': 'إدارة القوى العاملة والجداول',
    'employees.add.employee': 'إضافة موظف',
    'employees.tab.employees': 'الموظفون',
    'employees.tab.schedule': 'الجدول',
    'employees.stats.total': 'إجمالي الموظفين',
    'employees.stats.active.today': 'نشط اليوم',
    'employees.stats.weekly.payroll': 'كشف الراتب الأسبوعي',
    'employees.stats.avg.performance': 'متوسط الأداء',
    'employees.search.placeholder': 'البحث في الموظفين...',
    'employees.filter.all.departments': 'جميع الأقسام',
    'employees.department.management': 'الإدارة',
    'employees.department.sales': 'المبيعات',
    'employees.department.inventory': 'المخزون',
    'employees.department.pharmacy': 'الصيدلية',
    'employees.department.security': 'الأمن',
    'employees.hourly.rate': 'الأجر بالساعة',
    'employees.this.week': 'هذا الأسبوع',
    'employees.department': 'القسم',
    'employees.performance': 'الأداء',
    'employees.edit.details': 'تعديل التفاصيل',
    'employees.view.schedule': 'عرض الجدول',
    'employees.weekly.schedule': 'الجدول الأسبوعي',
    'employees.employee': 'الموظف',
    'employees.monday': 'الاثنين',
    'employees.tuesday': 'الثلاثاء',
    'employees.wednesday': 'الأربعاء',
    'employees.thursday': 'الخميس',
    'employees.friday': 'الجمعة',
    'employees.saturday': 'السبت',
    'employees.sunday': 'الأحد',
    'employees.off': 'إجازة',
    'employees.add.title': 'إضافة موظف جديد',
    'employees.form.full.name': 'الاسم الكامل',
    'employees.form.full.name.placeholder': 'أدخل الاسم الكامل',
    'employees.form.position': 'المنصب',
    'employees.form.position.placeholder': 'المنصب الوظيفي',
    'employees.form.department': 'القسم',
    'employees.form.hourly.rate': 'الأجر بالساعة',
    'employees.form.hourly.rate.placeholder': '0.00',
    'employees.form.email': 'البريد الإلكتروني',
    'employees.form.email.placeholder': 'employee@store.com',
    'employees.form.phone': 'الهاتف',
    'employees.form.phone.placeholder': '+1 (555) 123-4567',
    'employees.form.hire.date': 'تاريخ التوظيف',
    'employees.form.shift': 'الوردية',
    'employees.form.shift.placeholder': '9:00 صباحاً - 5:00 مساءً',
    'employees.form.cancel': 'إلغاء',
    'employees.form.add': 'إضافة موظف'
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  // Load language from localStorage on mount
  React.useEffect(() => {
    const savedLanguage = localStorage.getItem('pos-language') as Language;
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'ar')) {
      setLanguageState(savedLanguage);
    }
  }, []);

  // Save language to localStorage when it changes
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('pos-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      <div className={language === 'ar' ? 'rtl' : 'ltr'} dir={language === 'ar' ? 'rtl' : 'ltr'}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};