import React, {
  createContext,
  useContext,
  useState,
  useEffect,
  ReactNode,
} from "react";

export type Language = "en" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

interface LanguageProviderProps {
  children: ReactNode;
}

// Translation dictionaries
const translations: Record<Language, { [key: string]: string }> = {
  en: {
    "pos.select.client": "Select customer",
    "client.modal.title": "Select Customer",
    "payment.total.amount": "Total Amount",
    "payment.cash.received": "Cash Received",
    "payment.enter.amount": "Enter amount received",
    "payment.processing.button": "Processing...",
    "payment.complete": "Complete Payment",
    "payment.cancel": "Cancel",
    "payment.title": "Payment",
    "payment.exact.amount": "Exact Amount",
    "receipt.title": "Receipt",
    "receipt.store.name": "Store Name",
    "receipt.store.address": "Store Address",
    "receipt.store.phone": "Store Phone",
    "receipt.transaction.id": "Transaction ID",
    "receipt.date.time": "Date & Time",
    "receipt.cashier": "Cashier",
    "receipt.client": "Customer",
    "receipt.items.purchased": "Items Purchased",
    "receipt.total": "Total",
    "receipt.payment.method": "Payment Method",
    "receipt.amount.paid": "Amount Paid",
    "receipt.thank.you": "Thank you for your purchase!",
    "receipt.keep.receipt": "Please keep this receipt for your records.",
    "receipt.loyalty.points": "Loyalty Points:",
    "receipt.print": "Print",
    "receipt.email": "Email",
    "receipt.download": "Download PDF",
    "receipt.new.transaction": "New Transaction",
    "customers.invoice.create.due": "Create Invoice (Mark as Due)",
    "customers.invoice.due.amount": "Due Amount",
    // Invoice Modal
    "customers.invoice.step": "Step",
    "customers.invoice.of": "of",
    "customers.invoice.search.products": "Search products...",
    "customers.invoice.items": "Invoice Items",
    "customers.invoice.items.label": "items",
    "customers.invoice.no.items": "No items added",
    "customers.invoice.subtotal": "Subtotal:",
    "customers.invoice.tax": "Tax (8%):",
    "customers.invoice.total": "Total:",
    "customers.invoice.review.button": "Review Invoice",
    "customers.invoice.review.title": "Invoice Review",
    "customers.invoice.bill.to": "Bill To:",
    "customers.invoice.back.to.products": "Back to Products",
    "customers.invoice.proceed.to.payment": "Proceed to Payment",
    "customers.invoice.payment.title": "Payment",
    "customers.invoice.total.amount": "Total Amount",
    "customers.invoice.payment.method": "Payment Method",
    "customers.invoice.amount.paid": "Amount Paid",
    "customers.invoice.exact.amount": "Exact Amount",
    "customers.invoice.rounded.amount": "Rounded Amount",
    "customers.invoice.change": "Change",
    "customers.invoice.back": "Back",
    "customers.invoice.creating": "Creating...",
    "customers.invoice.create": "Create Invoice",
    // Header
    "header.title": "POS",
    "header.subtitle": "Point of Sale System",
    "header.cashier": "Cashier",

    // Auth
    "auth.login.title": "Sign in to your account",
    "auth.signup.title": "Create your account",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.full.name": "Full Name",
    "auth.employee.id": "Employee ID",
    "auth.role": "Role",
    "auth.confirm.password": "Confirm Password",
    "auth.login.button": "Sign In",
    "auth.signup.button": "Create Account",
    "auth.signing.in": "Signing in...",
    "auth.creating.account": "Creating account...",
    "auth.loading": "Loading...",
    "auth.placeholder.email": "Enter your email",
    "auth.placeholder.password": "Enter your password",
    "auth.placeholder.full.name": "Enter your full name",
    "auth.placeholder.employee.id": "Enter employee ID",
    "auth.placeholder.confirm.password": "Confirm your password",
    "auth.demo.credentials": "Demo Credentials",
    "auth.use.button": "Use",
    "auth.no.account": "Don't have an account?",
    "auth.have.account": "Already have an account?",
    "auth.signup.link": "Sign up",
    "auth.login.link": "Sign in",
    "auth.role.admin": "Admin",
    "auth.role.manager": "Manager",
    "auth.role.cashier": "Cashier",
    "auth.error.passwords.match": "Passwords do not match",
    "auth.error.password.length": "Password must be at least 6 characters",

    // Sidebar
    "sidebar.dashboard": "Dashboard",
    "sidebar.pos": "Point of Sale",
    "sidebar.inventory": "Inventory",
    "sidebar.inventoryManagement": "Inventory Management",
    "sidebar.transactions": "Transactions",
    "sidebar.categories": "Categories",
    "sidebar.suppliers": "Suppliers",
    "sidebar.users": "Users",
    "sidebar.employees": "Employees",
    "sidebar.clients": "Clients",
    "sidebar.customers": "Customers",
    "sidebar.reports": "Reports",
    "sidebar.profile": "Profile",
    "sidebar.settings": "Settings",
    "sidebar.logout": "Logout",
    "sidebar.cashier.role": "Cashier",
    "sidebar.logout.confirm.title": "Confirm Logout",
    "sidebar.logout.confirm.message": "Are you sure you want to logout?",
    "sidebar.logout.cancel": "Cancel",
    "sidebar.logout.confirm.button": "Logout",

    // Cart
    "cart.title": "Shopping Cart",
    "cart.items": "items",
    "cart.items.in.cart": "Items in cart",
    "cart.empty.title": "Your cart is empty",
    "cart.empty.subtitle": "Add products to get started",
    "cart.subtotal": "Subtotal",
    "cart.tax": "Tax",
    "cart.total": "Total",
    "cart.select.client": "Select Client",
    "cart.cash.payment": "Cash Payment",
    "cart.low.stock": "Low Stock",

    // Search
    "search.product.placeholder": "Search products...",
    "search.barcode.placeholder": "Scan or enter barcode/SKU...",
    "search.barcode.help": "Press Enter to search",
    "search.category.all": "All",

    // Categories
    "category.all": "All",
    "category.beverages": "Beverages",
    "category.bakery": "Bakery",
    "category.electronics": "Electronics",
    "category.produce": "Produce",
    "category.stationery": "Stationery",
    "category.clothing": "Clothing",
    "category.snacks": "Snacks",
    "category.health & beauty": "Health & Beauty",

    // Product
    "product.each": "each",

    // Payment
    "customers.title": "Customers",
    "customers.add.customer": "Add Customer",
    "customers.add.title": "Add New Customer",
    "customers.edit.title": "Edit Customer",
    "customers.view.title": "View Customer",
    "customers.delete.confirm":
      "Are you sure you want to delete this customer?",
    "customers.search.placeholder": "Search customers...",
    "customers.filter.all.status": "All Status",
    "customers.status.active": "Active",
    "customers.status.inactive": "Inactive",
    "customers.total.revenue": "Total Revenue",
    "customers.projects": "Projects",
    "customers.active.invoices": "Active Invoices",
    "customers.last.transaction": "Last Transaction",
    "customers.create.invoice": "Create Invoice",
    "customers.view.details": "View Details",
    "customers.empty.title": "No customers found",
    "customers.empty.subtitle": "Add customers to get started",
    "customers.stats.active": "Active Customers",
    "customers.stats.total.revenue": "Total Revenue",
    "customers.stats.active.invoices": "Active Invoices",
    "customers.stats.this.month": "This Month",
    "customers.stats.new.customers": "New Customers",
    "customers.form.company.name": "Company Name",
    "customers.form.email": "Email",
    "customers.form.phone": "Phone",
    "customers.form.address": "Address",
    "customers.form.notes": "Notes",
    "customers.form.status": "Status",
    "customers.form.company.placeholder": "Enter company name",
    "customers.form.email.placeholder": "Enter email address",
    "customers.form.phone.placeholder": "Enter phone number",
    "customers.form.address.placeholder": "Enter address",
    "customers.form.notes.placeholder": "Enter notes",
    "customers.form.cancel": "Cancel",
    "customers.form.add": "Add Customer",
    "customers.form.save": "Save Changes",
    "customers.form.adding": "Adding...",
    "customers.form.saving": "Saving...",
    "customers.actions.edit": "Edit",
    "customers.actions.delete": "Delete",
    "customers.actions.view": "View",
    "client.modal.addNew": "Add New Client",
    "client.search.placeholder": "Search clients...",
    "client.form.name": "Client Name",
    "client.form.email": "Email",
    "client.form.phone": "Phone",
    "client.form.namePlaceholder": "Enter client name",
    "client.form.emailPlaceholder": "Enter email address",
    "client.form.phonePlaceholder": "Enter phone number",

    // Customer Modal
    "customer.title": "Select Customer",
    "customer.search": "Search customers...",
    "customer.walk.in": "Walk-in Customer",
    "customer.walk.in.desc": "No customer information",
    "customer.points": "points",
    "customer.add.new": "Add New Customer",
    "customer.add.title": "Add New Customer",
    "customer.name.required": "Customer Name *",
    "customer.email.required": "Email Address *",
    "customer.phone": "Phone Number",
    "customer.name.placeholder": "Enter customer name",
    "customer.email.placeholder": "Enter email address",
    "customer.phone.placeholder": "Enter phone number",
    "customer.cancel": "Cancel",
    "customer.add": "Add Customer",

    // Loading
    "loading.store.data": "Loading store data...",
    "loading.inventory": "Loading inventory...",
    "loading.categories": "Loading categories...",
    "loading.suppliers": "Loading suppliers...",
    "loading.users": "Loading users...",
    "loading.employees": "Loading employees...",
    "loading.clients": "Loading clients...",
    "loading.profile": "Loading profile...",

    // Common
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.saving": "Saving...",
    "common.add": "Add",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.view": "View",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.actions": "Actions",
    "common.status": "Status",
    "common.active": "Active",
    "common.inactive": "Inactive",

  // Customer Modal
  "customer.modal.noClient": "No customer selected",
  "customer.modal.walkIn": "Walk-in customer",

    // Employees
    "employees.title": "Employees",
    "employees.add.employee": "Add Employee",
    "employees.add.title": "Add New Employee",
    "employees.edit.title": "Edit Employee",
    "employees.view.title": "View Employee",
    "employees.delete.confirm":
      "Are you sure you want to delete this employee?",
    "employees.search.placeholder": "Search employees...",
    "employees.filter.all.departments": "All Departments",
    "employees.department.management": "Management",
    "employees.department.sales": "Sales",
    "employees.department.inventory": "Inventory",
    "employees.department.pharmacy": "Pharmacy",
    "employees.department.security": "Security",
    "employees.department.customer.service": "Customer Service",
    "employees.status.active": "Active",
    "employees.status.inactive": "Inactive",
    "employees.status.terminated": "Terminated",
    "employees.hourly.rate": "Hourly Rate",
    "employees.this.week": "This Week",
    "employees.department": "Department",
    "employees.performance": "Performance",
    "employees.edit.details": "Edit Details",
    "employees.view.details": "View Details",
    "employees.view.schedule": "View Schedule",
    "employees.delete": "Delete",
    "employees.empty.title": "No employees found",
    "employees.empty.subtitle": "Add employees to get started",
    "employees.stats.total": "Total Employees",
    "employees.stats.active.today": "Active Today",
    "employees.stats.weekly.payroll": "Weekly Payroll",
    "employees.stats.avg.performance": "Avg Performance",
    "employees.tab.employees": "Employees",
    "employees.tab.schedule": "Schedule",
    "employees.weekly.schedule": "Weekly Schedule",
    "employees.employee": "Employee",
    "employees.monday": "Monday",
    "employees.tuesday": "Tuesday",
    "employees.wednesday": "Wednesday",
    "employees.thursday": "Thursday",
    "employees.friday": "Friday",
    "employees.saturday": "Saturday",
    "employees.sunday": "Sunday",
    "employees.off": "Off",
    "employees.form.full.name": "Full Name",
    "employees.form.position": "Position",
    "employees.form.department": "Department",
    "employees.form.email": "Email",
    "employees.form.phone": "Phone",
    "employees.form.employee.id": "Employee ID",
    "employees.form.hourly.rate": "Hourly Rate",
    "employees.form.shift": "Shift",
    "employees.form.hire.date": "Hire Date",
    "employees.form.status": "Status",
    "employees.form.hours.this.week": "Hours This Week",
    "employees.form.performance": "Performance (%)",
    "employees.form.full.name.placeholder": "Enter full name",
    "employees.form.position.placeholder": "Enter position",
    "employees.form.email.placeholder": "Enter email address",
    "employees.form.phone.placeholder": "Enter phone number",
    "employees.form.employee.id.placeholder": "Enter employee ID",
    "employees.form.hourly.rate.placeholder": "Enter hourly rate",
    "employees.form.shift.placeholder": "e.g., 9:00 AM - 5:00 PM",
    "employees.form.cancel": "Cancel",
    "employees.form.add": "Add Employee",
    "employees.form.save": "Save Changes",
    "employees.form.adding": "Adding...",
    "employees.form.saving": "Saving...",

    // Clients
    "clients.title": "Clients",
    "clients.add.client": "Add Client",
    "clients.add.title": "Add New Client",
    "clients.edit.title": "Edit Client",
    "clients.view.title": "View Client",
    "clients.delete.confirm": "Are you sure you want to delete this client?",
    "clients.search.placeholder": "Search clients...",
    "clients.filter.all.status": "All Status",
    "clients.status.active": "Active",
    "clients.status.inactive": "Inactive",
    "clients.total.revenue": "Total Revenue",
    "clients.projects": "Projects",
    "clients.active.invoices": "Active Invoices",
    "clients.last.transaction": "Last Transaction",
    "clients.create.invoice": "Create Invoice",
    "clients.view.details": "View Details",
    "clients.empty.title": "No clients found",
    "clients.empty.subtitle": "Add clients to get started",
    "clients.stats.active": "Active Clients",
    "clients.stats.total.revenue": "Total Revenue",
    "clients.stats.active.invoices": "Active Invoices",
    "clients.stats.this.month": "This Month",
    "clients.stats.new.clients": "New Clients",
    "clients.form.company.name": "Company Name",
    "clients.form.email": "Email",
    "clients.form.phone": "Phone",
    "clients.form.address": "Address",
    "clients.form.notes": "Notes",
    "clients.form.status": "Status",
    "clients.form.company.placeholder": "Enter company name",
    "clients.form.email.placeholder": "Enter email address",
    "clients.form.phone.placeholder": "Enter phone number",
    "clients.form.address.placeholder": "Enter address",
    "clients.form.notes.placeholder": "Enter notes",
    "clients.form.cancel": "Cancel",
    "clients.form.add": "Add Client",
    "clients.form.save": "Save Changes",
    "clients.form.adding": "Adding...",
    "clients.form.saving": "Saving...",
    "clients.actions.edit": "Edit",
    "clients.actions.delete": "Delete",
    "clients.actions.view": "View",

    // Orders
    "transactions.title": "Transactions",
    "transactions.search.placeholder": "Search transactions...",
    "transactions.filter.all": "All Transactions",
    "transactions.filter.completed": "Completed",
    "transactions.filter.pending": "Pending",
    "transactions.filter.cancelled": "Cancelled",
    "transactions.filter.due": "Due",
    "transactions.stats.total": "Total Transactions",
    "transactions.stats.completed": "Completed",
    "transactions.stats.pending": "Pending",
    "transactions.stats.due": "Due",
    "transactions.stats.revenue": "Total Revenue",
    "transactions.table.transaction": "Transaction",
    "transactions.table.customer": "Customer",
    "transactions.table.items": "Items",
    "transactions.table.total": "Total",
    "transactions.table.amountPaid": "Amount Paid",
    "transactions.table.amountDue": "Amount Due",
    "transactions.table.status": "Status",
    "transactions.table.date": "Date",
    "transactions.table.actions": "Actions",
    "transactions.table.items.count": "items",
    "transactions.status.completed": "Completed",
    "transactions.status.pending": "Pending",
    "transactions.status.due": "Due",
    "transactions.status.cancelled": "Cancelled",
    "transactions.actions.view": "View",
    "transactions.actions.print": "Print",
    "transactions.actions.update": "Update",
    "transactions.actions.update.success": "Transaction updated successfully!",
    "transactions.actions.print.success": "Receipt printed successfully!",
    "transactions.empty.title": "No transactions found",
    "transactions.empty.subtitle":
      "Transactions will appear here once customers make purchases",
    "transactions.detail.title": "Transaction Details",
    "transactions.detail.transaction.id": "Transaction ID",
    "transactions.detail.status": "Status",
    "transactions.detail.customer": "Customer",
    "transactions.detail.date": "Date",
    "transactions.detail.items": "Items",
    "transactions.detail.total": "Total",
    "transactions.detail.payment.method": "Payment Method",
    "transactions.detail.close": "Close",
    "transactions.loading": "Loading transactions...",

    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.stats.today.sales": "Today's Sales",
    "dashboard.stats.active.employees": "Active Employees",
    "dashboard.stats.low.stock": "Low Stock Items",
    "dashboard.stats.orders.today": "Orders Today",
    "dashboard.recent.sales": "Recent Sales",
    "dashboard.alerts.notifications": "Alerts & Notifications",
    "dashboard.current.shift": "Current Shift",
    "dashboard.quick.actions": "Quick Actions",
    "dashboard.new.sale": "New Sale",
    "dashboard.add.inventory": "Add Inventory",
    "dashboard.schedule.staff": "Schedule Staff",
    "dashboard.view.reports": "View Reports",
    "dashboard.on.duty": "On Duty",
    "dashboard.starts.at": "Starts at",
    "dashboard.view.all.notifications": "View all notifications",
    "dashboard.items": "items",
    "loading.dashboard": "Loading dashboard...",
    "dashboard.unknown.cashier": "Unknown cashier",
    "dashboard.walkin.customer": "Walk-in Customer",
    "dashboard.low.stock.alert":
      "{name} stock running low ({stock} units left)",

    // Users
    "users.title": "Users",
    "users.add.user": "Add User",
    "users.add.title": "Add New User",
    "users.edit.title": "Edit User",
    "users.view.title": "View User",
    "users.delete.confirm": "Are you sure you want to delete this user?",
    "users.search.placeholder": "Search users...",
    "users.filter.all.roles": "All Roles",
    "users.filter.all.status": "All Status",
    "users.status.active": "Active",
    "users.status.inactive": "Inactive",
    "users.stats.total": "Total Users",
    "users.stats.active": "Active Users",
    "users.stats.admins": "Admins",
    "users.stats.managers": "Managers",
    "users.table.user": "User",
    "users.table.contact": "Contact",
    "users.table.role": "Role",
    "users.table.status": "Status",
    "users.table.last.login": "Last Login",
    "users.table.actions": "Actions",
    "users.actions.edit": "Edit",
    "users.actions.delete": "Delete",
    "users.actions.view": "View",
    "users.empty.title": "No users found",
    "users.empty.subtitle": "Add users to get started",
    "users.form.name": "Full Name",
    "users.form.email": "Email",
    "users.form.phone": "Phone",
    "users.form.employee.id": "Employee ID",
    "users.form.password": "Password",
    "users.form.role": "Role",
    "users.form.status": "Status",
    "users.form.name.placeholder": "Enter full name",
    "users.form.email.placeholder": "Enter email address",
    "users.form.phone.placeholder": "Enter phone number",
    "users.form.employee.id.placeholder": "Enter employee ID",
    "users.form.password.placeholder": "Enter password",
    "users.form.cancel": "Cancel",
    "users.form.add": "Add User",
    "users.form.save": "Save Changes",
    "users.form.adding": "Adding...",
    "users.form.saving": "Saving...",
    "users.info.last.login": "Last Login",
    "users.info.created": "Created",
    "users.info.updated": "Updated",
    "users.access.denied.title": "Access Denied",
    "users.access.denied.message":
      "You do not have permission to access this page",

    // Categories
    "categories.title": "Categories",
    "categories.add.category": "Add Category",
    "categories.add.title": "Add New Category",
    "categories.edit.title": "Edit Category",
    "categories.view.title": "View Category",
    "categories.delete.confirm":
      "Are you sure you want to delete this category?",
    "categories.search.placeholder": "Search categories...",
    "categories.stats.total": "Total Categories",
    "categories.stats.products": "Total Products",
    "categories.stats.average": "Avg per Category",
    "categories.products": "products",
    "categories.updated": "Updated",
    "categories.empty.title": "No categories found",
    "categories.empty.subtitle": "Add categories to organize your products",
    "categories.form.name": "Category Name",
    "categories.form.description": "Description",
    "categories.form.color": "Color",
    "categories.form.image": "Category Image",
    "categories.form.name.placeholder": "Enter category name",
    "categories.form.description.placeholder": "Enter category description",
    "categories.form.image.choose": "Choose Image",
    "categories.form.image.remove": "Remove Image",
    "categories.form.image.help": "Max 5MB, JPG/PNG/GIF",
    "categories.form.cancel": "Cancel",
    "categories.form.add": "Add Category",
    "categories.form.save": "Save Changes",
    "categories.form.adding": "Adding...",
    "categories.form.saving": "Saving...",
    "categories.actions.edit": "Edit",
    "categories.actions.delete": "Delete",
    "categories.actions.view": "View",
    "categories.info.products": "Products",
    "categories.info.created": "Created",
    "categories.info.updated": "Updated",

    // Suppliers
    "suppliers.title": "Suppliers",
    "suppliers.add.supplier": "Add Supplier",
    "suppliers.add.title": "Add New Supplier",
    "suppliers.edit.title": "Edit Supplier",
    "suppliers.view.title": "View Supplier",
    "suppliers.delete.confirm":
      "Are you sure you want to delete this supplier?",
    "suppliers.search.placeholder": "Search suppliers...",
    "suppliers.filter.all.status": "All Status",
    "suppliers.status.active": "Active",
    "suppliers.status.inactive": "Inactive",
    "suppliers.stats.total": "Total Suppliers",
    "suppliers.stats.active": "Active Suppliers",
    "suppliers.stats.products": "Total Products",
    "suppliers.stats.average": "Avg per Supplier",
    "suppliers.table.supplier": "Supplier",
    "suppliers.table.contact": "Contact",
    "suppliers.table.location": "Location",
    "suppliers.table.products": "Products",
    "suppliers.table.status": "Status",
    "suppliers.table.actions": "Actions",
    "suppliers.products.supplied": "products supplied",
    "suppliers.actions.edit": "Edit",
    "suppliers.actions.delete": "Delete",
    "suppliers.actions.view": "View",
    "suppliers.empty.title": "No suppliers found",
    "suppliers.empty.subtitle": "Add suppliers to manage your inventory",
    "suppliers.form.name": "Supplier Name",
    "suppliers.form.contact.person": "Contact Person",
    "suppliers.form.email": "Email",
    "suppliers.form.phone": "Phone",
    "suppliers.form.address": "Street Address",
    "suppliers.form.city": "City",
    "suppliers.form.state": "State",
    "suppliers.form.zip.code": "ZIP Code",
    "suppliers.form.country": "Country",
    "suppliers.form.payment.terms": "Payment Terms",
    "suppliers.form.status": "Status",
    "suppliers.form.name.placeholder": "Enter supplier name",
    "suppliers.form.contact.person.placeholder": "Enter contact person",
    "suppliers.form.email.placeholder": "Enter email address",
    "suppliers.form.phone.placeholder": "Enter phone number",
    "suppliers.form.address.placeholder": "Enter street address",
    "suppliers.form.city.placeholder": "Enter city",
    "suppliers.form.state.placeholder": "Enter state",
    "suppliers.form.zip.code.placeholder": "Enter ZIP code",
    "suppliers.form.country.placeholder": "Enter country",
    "suppliers.form.cancel": "Cancel",
    "suppliers.form.add": "Add Supplier",
    "suppliers.form.save": "Save Changes",
    "suppliers.form.adding": "Adding...",
    "suppliers.form.saving": "Saving...",
    "suppliers.info.products.supplied": "Products Supplied",
    "suppliers.info.created": "Created",
    "suppliers.info.updated": "Updated",

    // Inventory
    "inventory.title": "Inventory",
    "inventory.add.item": "Add Item",
    "inventory.add.title": "Add New Item",
    "inventory.edit.title": "Edit Item",
    "inventory.view.title": "View Item",
    "inventory.delete.confirm": "Are you sure you want to delete this item?",
    "inventory.search.placeholder": "Search inventory...",
    "inventory.filter.all.categories": "All Categories",
    "inventory.filter.all.stock": "All Stock",
    "inventory.filter.in.stock": "In Stock",
    "inventory.filter.low.stock": "Low Stock",
    "inventory.filter.out.of.stock": "Out of Stock",
    "inventory.stats.total.items": "Total Items",
    "inventory.stats.low.stock": "Low Stock",
    "inventory.stats.out.of.stock": "Out of Stock",
    "inventory.stats.total.value": "Total Value",
    "inventory.table.product": "Product",
    "inventory.table.sku": "SKU",
    "inventory.table.category": "Category",
    "inventory.table.stock": "Stock",
    "inventory.table.price": "Price",
    "inventory.table.supplier": "Supplier",
    "inventory.table.actions": "Actions",
    "inventory.last.restocked": "Last restocked",
    "inventory.actions.edit": "Edit",
    "inventory.actions.delete": "Delete",
    "inventory.actions.view": "View",
    "inventory.empty.title": "No inventory items found",
    "inventory.empty.subtitle": "Add items to manage your inventory",
    "inventory.form.name": "Product Name",
    "inventory.form.sku": "SKU",
    "inventory.form.category": "Category",
    "inventory.form.supplier": "Supplier",
    "inventory.form.cost.price": "Cost Price",
    "inventory.form.selling.price": "Selling Price",
    "inventory.form.stock": "Stock Quantity",
    "inventory.form.reorder.level": "Reorder Level",
    "inventory.form.description": "Description",
    "inventory.form.image": "Product Image",
    "inventory.form.name.placeholder": "Enter product name",
    "inventory.form.sku.placeholder": "Enter SKU",
    "inventory.form.description.placeholder": "Enter product description",
    "inventory.form.select.category": "Select Category",
    "inventory.form.select.supplier": "Select Supplier",
    "inventory.form.image.choose": "Choose Image",
    "inventory.form.image.remove": "Remove Image",
    "inventory.form.image.help": "Max 5MB, JPG/PNG/GIF",
    "inventory.form.cancel": "Cancel",
    "inventory.form.add": "Add Item",
    "inventory.form.save": "Save Changes",
    "inventory.form.adding": "Adding...",
    "inventory.form.saving": "Saving...",
    "inventory.info.supplier": "Supplier",
    "inventory.info.last.restocked": "Last Restocked",
    "inventory.info.created": "Created",

    // Profile
    "profile.title": "Profile",
    "profile.edit": "Edit Profile",
    "profile.save": "Save Changes",
    "profile.cancel": "Cancel",
    "profile.saving": "Saving...",
    "profile.personal.info": "Personal Information",
    "profile.work.info": "Work Information",
    "profile.performance": "Performance Stats",
    "profile.full.name": "Full Name",
    "profile.employee.id": "Employee ID",
    "profile.email": "Email",
    "profile.phone": "Phone",
    "profile.address": "Address",
    "profile.role": "Role",
    "profile.department": "Department",
    "profile.join.date": "Join Date",
    "profile.phone.placeholder": "Enter phone number",
    "profile.address.placeholder": "Enter address",
    "profile.phone.not.set": "Not set",
    "profile.name.readonly": "Contact admin to change name",
    "profile.email.readonly": "Contact admin to change email",
    "profile.change.password": "Change Password",
    "profile.current.password": "Current Password",
    "profile.new.password": "New Password",
    "profile.confirm.password": "Confirm Password",
    "profile.current.password.placeholder": "Enter current password",
    "profile.new.password.placeholder": "Enter new password",
    "profile.confirm.password.placeholder": "Confirm new password",
    "profile.password.requirements":
      "Password must be at least 6 characters long",
    "profile.change.password.button": "Change Password",
    "profile.changing.password": "Changing...",
    "profile.update.success": "Profile updated successfully",
    "profile.password.change.success": "Password changed successfully",
    "profile.stats.total.sales": "Total Sales",
    "profile.stats.transactions": "Transactions",
    "profile.stats.days.active": "Days Active",
    "profile.stats.last.login": "Last Login",

    // Reports
    "reports.title": "Reports",
    "reports.overview": "Overview",
    "reports.sales": "Sales",
    "reports.inventory": "Inventory",
    "reports.customers": "Customers",
    "reports.products": "Products",
    "reports.date.today": "Today",
    "reports.date.yesterday": "Yesterday",
    "reports.date.week": "Last 7 Days",
    "reports.date.month": "Last 30 Days",
    "reports.date.quarter": "Last 3 Months",
    "reports.date.year": "Last Year",
    "reports.date.custom": "Custom Range",
    "reports.export.print": "Print",
    "reports.export.pdf": "PDF",
    "reports.export.excel": "Excel",
    "reports.export.csv": "CSV",
    "reports.export.success": "Report exported successfully!",
    "reports.metrics.total.sales": "Total Sales",
    "reports.metrics.transactions": "Transactions",
    "reports.metrics.customers": "Customers",
    "reports.metrics.avg.transaction": "Avg Transaction",
    "reports.chart.daily.sales": "Daily Sales",
    "reports.chart.top.products": "Top Products",
    "reports.chart.category.sales": "Category Sales",
    "reports.product.sold": "sold",
    "reports.table.date": "Date",
    "reports.table.sales": "Sales",
    "reports.table.transactions": "Transactions",
    "reports.table.customers": "Customers",
    "reports.table.avg.transaction": "Avg Transaction",
    "reports.inventory.total.items": "Total Items",
    "reports.inventory.low.stock": "Low Stock",
    "reports.inventory.out.of.stock": "Out of Stock",

    // Settings
    "settings.title": "Settings",
    "settings.tabs.store": "Store",
    "settings.tabs.system": "System",
    "settings.tabs.receipt": "Receipt",
    "settings.tabs.notifications": "Notifications",
    "settings.tabs.security": "Security",
    "settings.tabs.display": "Display",
    "settings.store.info": "Store Information",
    "settings.store.name": "Store Name",
    "settings.store.address": "Store Address",
    "settings.store.phone": "Store Phone",
    "settings.store.email": "Store Email",
    "settings.tax.settings": "Tax Settings",
    "settings.tax.rate": "Tax Rate",
    "settings.tax.included": "Tax Included in Prices",
    "settings.system.general": "General Settings",
    "settings.system.currency": "Currency",
    "settings.system.date.format": "Date Format",
    "settings.system.time.format": "Time Format",
    "settings.system.time.12": "12 Hour",
    "settings.system.time.24": "24 Hour",
    "settings.system.low.stock.threshold": "Low Stock Threshold",
    "settings.receipt.customization": "Receipt Customization",
    "settings.receipt.header": "Receipt Header",
    "settings.receipt.footer": "Receipt Footer",
    "settings.receipt.printing": "Printing Options",
    "settings.receipt.print.logo": "Print Logo on Receipt",
    "settings.receipt.auto.print": "Auto Print Receipts",
    "settings.notifications.alerts": "Alert Settings",
    "settings.notifications.low.stock": "Low Stock Alerts",
    "settings.notifications.email": "Email Notifications",
    "settings.notifications.sound": "Sound Effects",
    "settings.security.access": "Access Control",
    "settings.security.session.timeout": "Session Timeout",
    "settings.security.minutes": "minutes",
    "settings.security.password.change": "Require Regular Password Changes",
    "settings.security.two.factor": "Two-Factor Authentication",
    "settings.display.appearance": "Appearance",
    "settings.display.theme": "Theme",
    "settings.display.theme.light": "Light",
    "settings.display.theme.dark": "Dark",
    "settings.display.theme.auto": "Auto",
    "settings.display.compact.mode": "Compact Mode",
    "settings.display.product.images": "Show Product Images",
    "settings.save.changes": "Save Changes",
    "settings.reset.defaults": "Reset to Defaults",
    "settings.reset.confirm":
      "Are you sure you want to reset all settings to defaults?",
    "settings.saved.successfully": "Settings saved successfully",
    "settings.unsaved.changes": "You have unsaved changes",
  },
  ar: {
    "pos.select.client": "اختر الزبون",
    "client.modal.title": "اختر الزبون",
    "payment.total.amount": "المبلغ الإجمالي",
    "payment.cash.received": "المبلغ المستلم نقداً",
    "payment.enter.amount": "أدخل المبلغ المستلم",
    "payment.processing.button": "جاري المعالجة...",
    "payment.complete": "إتمام الدفع",
    "payment.cancel": "إلغاء",
    "payment.title": "الدفع",
    "payment.exact.amount": "المبلغ الكامل",
    "receipt.title": "الإيصال",
    "receipt.store.name": "اسم المتجر",
    "receipt.store.address": "عنوان المتجر",
    "receipt.store.phone": "هاتف المتجر",
    "receipt.transaction.id": "رقم العملية",
    "receipt.date.time": "التاريخ والوقت",
    "receipt.cashier": "الكاشير",
    "receipt.client": "العميل",
    "receipt.items.purchased": "العناصر المشتراة",
    "receipt.total": "الإجمالي",
    "receipt.payment.method": "طريقة الدفع",
    "receipt.amount.paid": "المبلغ المدفوع",
    "receipt.thank.you": "شكرًا لشرائك!",
    "receipt.keep.receipt": "يرجى الاحتفاظ بهذا الإيصال لسجلاتك.",
    "receipt.loyalty.points": "نقاط الولاء:",
    "receipt.print": "طباعة",
    "receipt.email": "إرسال بالبريد",
    "receipt.download": "تحميل PDF",
    "receipt.new.transaction": "عملية جديدة",
    "sidebar.transactions": "المعاملات",
    "customers.invoice.create.due": "إنشاء الفاتورة (تسجيل كمديونية)",
    "customers.invoice.due.amount": "المبلغ المستحق",
    // Invoice Modal
    "customers.invoice.step": "الخطوة",
    "customers.invoice.of": "من",
    "customers.invoice.search.products": "ابحث عن المنتجات...",
    "customers.invoice.items": "عناصر الفاتورة",
    "customers.invoice.items.label": "عنصر",
    "customers.invoice.no.items": "لم تتم إضافة عناصر",
    "customers.invoice.subtotal": "المجموع:",
    "customers.invoice.tax": "الضريبة (٨٪):",
    "customers.invoice.total": "الإجمالي:",
    "customers.invoice.review.button": "مراجعة الفاتورة",
    "customers.invoice.review.title": "مراجعة الفاتورة",
    "customers.invoice.bill.to": "فاتورة إلى:",
    "customers.invoice.back.to.products": "العودة للمنتجات",
    "customers.invoice.proceed.to.payment": "المتابعة للدفع",
    "customers.invoice.payment.title": "الدفع",
    "customers.invoice.total.amount": "المبلغ الإجمالي",
    "customers.invoice.payment.method": "طريقة الدفع",
    "customers.invoice.amount.paid": "المبلغ المدفوع",
    "customers.invoice.exact.amount": "المبلغ الكامل",
    "customers.invoice.rounded.amount": "المبلغ المقرب",
    "customers.invoice.change": "الباقي",
    "customers.invoice.back": "رجوع",
    "customers.invoice.creating": "جاري الإنشاء...",
    "customers.invoice.create": "إنشاء الفاتورة",
    // Header
    "header.title": "نقطة البيع",
    "header.subtitle": "نقطة البيع",
    "header.cashier": "أمين الصندوق",

    // Auth
    "auth.login.title": "تسجيل الدخول إلى حسابك",
    "auth.signup.title": "إنشاء حساب جديد",
    "auth.email": "البريد الإلكتروني",
    "auth.password": "كلمة المرور",
    "auth.full.name": "الاسم الكامل",
    "auth.employee.id": "رقم الموظف",
    "auth.role": "الدور",
    "auth.confirm.password": "تأكيد كلمة المرور",
    "auth.login.button": "تسجيل الدخول",
    "auth.signup.button": "إنشاء حساب",
    "auth.signing.in": "جاري تسجيل الدخول...",
    "auth.creating.account": "جاري إنشاء الحساب...",
    "auth.loading": "جاري التحميل...",
    "auth.placeholder.email": "أدخل بريدك الإلكتروني",
    "auth.placeholder.password": "أدخل كلمة المرور",
    "auth.placeholder.full.name": "أدخل اسمك الكامل",
    "auth.placeholder.employee.id": "أدخل رقم الموظف",
    "auth.placeholder.confirm.password": "أكد كلمة المرور",
    "auth.demo.credentials": "بيانات تجريبية",
    "auth.use.button": "استخدام",
    "auth.no.account": "ليس لديك حساب؟",
    "auth.have.account": "لديك حساب بالفعل؟",
    "auth.signup.link": "إنشاء حساب",
    "auth.login.link": "تسجيل الدخول",
    "auth.role.admin": "مدير",
    "auth.role.manager": "مدير قسم",
    "auth.role.cashier": "أمين صندوق",
    "auth.error.passwords.match": "كلمات المرور غير متطابقة",
    "auth.error.password.length": "كلمة المرور يجب أن تكون 6 أحرف على الأقل",

    // Sidebar
    "sidebar.dashboard": "لوحة التحكم",
    "sidebar.pos": "نقطة البيع",
    "sidebar.inventory": "المخزن",
    "sidebar.inventoryManagement": "إدارة المخزون",
    "sidebar.orders": "الطلبات",
    "sidebar.categories": "الفئات",
    "sidebar.suppliers": "الموردين",
    "sidebar.users": "المستخدمين",
    "sidebar.employees": "الموظفين",
    "sidebar.clients": "العملاء",
    "sidebar.customers": "العملاء",
    "sidebar.reports": "التقارير",
    "sidebar.profile": "الملف الشخصي",
    "sidebar.settings": "الإعدادات",
    "sidebar.logout": "تسجيل الخروج",
    "sidebar.cashier.role": "أمين صندوق",
    "sidebar.logout.confirm.title": "تأكيد تسجيل الخروج",
    "sidebar.logout.confirm.message": "هل أنت متأكد من تسجيل الخروج؟",
    "sidebar.logout.cancel": "إلغاء",
    "sidebar.logout.confirm.button": "تسجيل الخروج",

    // Cart
    "cart.title": "سلة التسوق",
    "cart.items": "عناصر",
    "cart.items.in.cart": "عناصر في السلة",
    "cart.empty.title": "سلة التسوق فارغة",
    "cart.empty.subtitle": "أضف منتجات للبدء",
    "cart.subtotal": "المجموع الفرعي",
    "cart.tax": "الضريبة",
    "cart.total": "المجموع",
    "cart.select.client": "اختر عميل",
    "cart.cash.payment": "دفع نقدي",
    "cart.low.stock": "مخزون منخفض",

    // Search
    "search.product.placeholder": "البحث عن المنتجات...",
    "search.barcode.placeholder": "مسح أو إدخال الباركود/SKU...",
    "search.barcode.help": "اضغط Enter للبحث",
    "search.category.all": "الكل",

    // Categories
    "category.all": "الكل",
    "category.beverages": "المشروبات",
    "category.bakery": "المخبوزات",
    "category.electronics": "الإلكترونيات",
    "category.produce": "المنتجات الطازجة",
    "category.stationery": "القرطاسية",
    "category.clothing": "الملابس",
    "category.snacks": "الوجبات الخفيفة",
    "category.health & beauty": "الصحة والجمال",

    // Product
    "product.each": "للقطعة",

    // Payment
    "customers.title": "العملاء",
    "customers.add.customer": "إضافة عميل",
    "customers.add.title": "إضافة عميل جديد",
    "customers.edit.title": "تعديل العميل",
    "customers.view.title": "عرض العميل",
    "customers.delete.confirm": "هل أنت متأكد من حذف هذا العميل؟",
    "customers.search.placeholder": "البحث عن العملاء...",
    "customers.filter.all.status": "جميع الحالات",
    "customers.status.active": "نشط",
    "customers.status.inactive": "غير نشط",
    "customers.total.revenue": "إجمالي الإيرادات",
    "customers.projects": "المشاريع",
    "customers.active.invoices": "الفواتير النشطة",
    "customers.last.transaction": "آخر معاملة",
    "customers.create.invoice": "إنشاء فاتورة",
    "customers.view.details": "عرض التفاصيل",
    "customers.empty.title": "لم يتم العثور على عملاء",
    "customers.empty.subtitle": "أضف عملاء للبدء",
    "customers.stats.active": "العملاء النشطين",
    "customers.stats.total.revenue": "إجمالي الإيرادات",
    "customers.stats.active.invoices": "الفواتير النشطة",
    "customers.stats.this.month": "هذا الشهر",
    "customers.stats.new.customers": "عملاء جدد",
    "customers.form.company.name": "اسم الشركة",
    "customers.form.email": "البريد الإلكتروني",
    "customers.form.phone": "الهاتف",
    "customers.form.address": "العنوان",
    "customers.form.notes": "ملاحظات",
    "customers.form.status": "الحالة",
    "customers.form.company.placeholder": "أدخل اسم الشركة",
    "customers.form.email.placeholder": "أدخل البريد الإلكتروني",
    "customers.form.phone.placeholder": "أدخل رقم الهاتف",
    "customers.form.address.placeholder": "أدخل العنوان",
    "customers.form.notes.placeholder": "أدخل ملاحظات",
    "customers.form.cancel": "إلغاء",
    "customers.form.add": "إضافة عميل",
    "customers.form.save": "حفظ التغييرات",
    "customers.form.adding": "جاري الإضافة...",
    "customers.form.saving": "جاري الحفظ...",
    "customers.actions.edit": "تعديل",
    "customers.actions.delete": "حذف",
    "customers.actions.view": "عرض",
    "client.modal.addNew": "إضافة عميل جديد",
    "client.search.placeholder": "البحث عن العملاء...",
    "client.form.name": "اسم العميل",
    "client.form.email": "البريد الإلكتروني",
    "client.form.phone": "الهاتف",
    "client.form.namePlaceholder": "أدخل اسم العميل",
    "client.form.emailPlaceholder": "أدخل البريد الإلكتروني",
    "client.form.phonePlaceholder": "أدخل رقم الهاتف",

    // Customer Modal
    "customer.title": "اختيار العميل",
    "customer.search": "البحث عن العملاء...",
    "customer.walk.in": "عميل عادي",
    "customer.walk.in.desc": "بدون معلومات عميل",
    "customer.points": "نقاط",
    "customer.add.new": "إضافة عميل جديد",
    "customer.add.title": "إضافة عميل جديد",
    "customer.name.required": "اسم العميل *",
    "customer.email.required": "البريد الإلكتروني *",
    "customer.phone": "رقم الهاتف",
    "customer.name.placeholder": "أدخل اسم العميل",
    "customer.email.placeholder": "أدخل البريد الإلكتروني",
    "customer.phone.placeholder": "أدخل رقم الهاتف",
    "customer.cancel": "إلغاء",
    "customer.add": "إضافة عميل",

    // Loading
    "loading.store.data": "جاري تحميل بيانات المتجر...",
    "loading.inventory": "جاري تحميل المخزن...",
    "loading.categories": "جاري تحميل الفئات...",
    "loading.suppliers": "جاري تحميل الموردين...",
    "loading.users": "جاري تحميل المستخدمين...",
    "loading.employees": "جاري تحميل الموظفين...",
    "loading.clients": "جاري تحميل العملاء...",
    "loading.profile": "جاري تحميل الملف الشخصي...",

    // Common
    "common.cancel": "إلغاء",
    "common.save": "حفظ",
    "common.saving": "جاري الحفظ...",
    "common.add": "إضافة",
    "common.edit": "تعديل",
    "common.delete": "حذف",
    "common.view": "عرض",
    "common.search": "بحث",
    "common.filter": "تصفية",
    "common.actions": "الإجراءات",
    "common.status": "الحالة",
    "common.active": "نشط",
    "common.inactive": "غير نشط",

  // Customer Modal
  "customer.modal.noClient": "لم يتم اختيار عميل",
  "customer.modal.walkIn": "عميل مباشر",

    // Employees
    "employees.title": "الموظفين",
    "employees.add.employee": "إضافة موظف",
    "employees.add.title": "إضافة موظف جديد",
    "employees.edit.title": "تعديل الموظف",
    "employees.view.title": "عرض الموظف",
    "employees.delete.confirm": "هل أنت متأكد من حذف هذا الموظف؟",
    "employees.search.placeholder": "البحث عن الموظفين...",
    "employees.filter.all.departments": "جميع الأقسام",
    "employees.department.management": "الإدارة",
    "employees.department.sales": "المبيعات",
    "employees.department.inventory": "المخزن",
    "employees.department.pharmacy": "الصيدلية",
    "employees.department.security": "الأمن",
    "employees.department.customer.service": "خدمة العملاء",
    "employees.status.active": "نشط",
    "employees.status.inactive": "غير نشط",
    "employees.status.terminated": "منتهي الخدمة",
    "employees.hourly.rate": "الأجر بالساعة",
    "employees.this.week": "هذا الأسبوع",
    "employees.department": "القسم",
    "employees.performance": "الأداء",
    "employees.edit.details": "تعديل التفاصيل",
    "employees.view.details": "عرض التفاصيل",
    "employees.view.schedule": "عرض الجدول",
    "employees.delete": "حذف",
    "employees.empty.title": "لم يتم العثور على موظفين",
    "employees.empty.subtitle": "أضف موظفين للبدء",
    "employees.stats.total": "إجمالي الموظفين",
    "employees.stats.active.today": "نشط اليوم",
    "employees.stats.weekly.payroll": "الراتب الأسبوعي",
    "employees.stats.avg.performance": "متوسط الأداء",
    "employees.tab.employees": "الموظفين",
    "employees.tab.schedule": "الجدول",
    "employees.weekly.schedule": "الجدول الأسبوعي",
    "employees.employee": "الموظف",
    "employees.monday": "الاثنين",
    "employees.tuesday": "الثلاثاء",
    "employees.wednesday": "الأربعاء",
    "employees.thursday": "الخميس",
    "employees.friday": "الجمعة",
    "employees.saturday": "السبت",
    "employees.sunday": "الأحد",
    "employees.off": "إجازة",
    "employees.form.full.name": "الاسم الكامل",
    "employees.form.position": "المنصب",
    "employees.form.department": "القسم",
    "employees.form.email": "البريد الإلكتروني",
    "employees.form.phone": "الهاتف",
    "employees.form.employee.id": "رقم الموظف",
    "employees.form.hourly.rate": "الأجر بالساعة",
    "employees.form.shift": "الوردية",
    "employees.form.hire.date": "تاريخ التوظيف",
    "employees.form.status": "الحالة",
    "employees.form.hours.this.week": "ساعات هذا الأسبوع",
    "employees.form.performance": "الأداء (%)",
    "employees.form.full.name.placeholder": "أدخل الاسم الكامل",
    "employees.form.position.placeholder": "أدخل المنصب",
    "employees.form.email.placeholder": "أدخل البريد الإلكتروني",
    "employees.form.phone.placeholder": "أدخل رقم الهاتف",
    "employees.form.employee.id.placeholder": "أدخل رقم الموظف",
    "employees.form.hourly.rate.placeholder": "أدخل الأجر بالساعة",
    "employees.form.shift.placeholder": "مثال: 9:00 ص - 5:00 م",
    "employees.form.cancel": "إلغاء",
    "employees.form.add": "إضافة موظف",
    "employees.form.save": "حفظ التغييرات",
    "employees.form.adding": "جاري الإضافة...",
    "employees.form.saving": "جاري الحفظ...",

    // Clients
    "clients.title": "العملاء",
    "clients.add.client": "إضافة عميل",
    "clients.add.title": "إضافة عميل جديد",
    "clients.edit.title": "تعديل العميل",
    "clients.view.title": "عرض العميل",
    "clients.delete.confirm": "هل أنت متأكد من حذف هذا العميل؟",
    "clients.search.placeholder": "البحث عن العملاء...",
    "clients.filter.all.status": "جميع الحالات",
    "clients.status.active": "نشط",
    "clients.status.inactive": "غير نشط",
    "clients.total.revenue": "إجمالي الإيرادات",
    "clients.projects": "المشاريع",
    "clients.active.invoices": "الفواتير النشطة",
    "clients.last.transaction": "آخر معاملة",
    "clients.create.invoice": "إنشاء فاتورة",
    "clients.view.details": "عرض التفاصيل",
    "clients.empty.title": "لم يتم العثور على عملاء",
    "clients.empty.subtitle": "أضف عملاء للبدء",
    "clients.stats.active": "العملاء النشطين",
    "clients.stats.total.revenue": "إجمالي الإيرادات",
    "clients.stats.active.invoices": "الفواتير النشطة",
    "clients.stats.this.month": "هذا الشهر",
    "clients.stats.new.clients": "عملاء جدد",
    "clients.form.company.name": "اسم الشركة",
    "clients.form.email": "البريد الإلكتروني",
    "clients.form.phone": "الهاتف",
    "clients.form.address": "العنوان",
    "clients.form.notes": "ملاحظات",
    "clients.form.status": "الحالة",
    "clients.form.company.placeholder": "أدخل اسم الشركة",
    "clients.form.email.placeholder": "أدخل البريد الإلكتروني",
    "clients.form.phone.placeholder": "أدخل رقم الهاتف",
    "clients.form.address.placeholder": "أدخل العنوان",
    "clients.form.notes.placeholder": "أدخل ملاحظات",
    "clients.form.cancel": "إلغاء",
    "clients.form.add": "إضافة عميل",
    "clients.form.save": "حفظ التغييرات",
    "clients.form.adding": "جاري الإضافة...",
    "clients.form.saving": "جاري الحفظ...",
    "clients.actions.edit": "تعديل",
    "clients.actions.delete": "حذف",
    "clients.actions.view": "عرض",

    // Orders
    "transactions.title": "المعاملات",
    "transactions.search.placeholder": "البحث في المعاملات...",
    "transactions.filter.all": "جميع المعاملات",
    "transactions.filter.completed": "مكتملة",
    "transactions.filter.pending": "معلقة",
    "transactions.filter.cancelled": "ملغية",
    "transactions.filter.due": "متبقي",
    "transactions.stats.total": "إجمالي المعاملات",
    "transactions.stats.completed": "مكتملة",
    "transactions.stats.pending": "معلقة",
    "transactions.stats.due": "متبقي",
    "transactions.stats.revenue": "إجمالي الإيرادات",
    "transactions.table.transaction": "المعاملة",
    "transactions.table.customer": "العميل",
    "transactions.table.items": "العناصر",
    "transactions.table.total": "المجموع",
    "transactions.table.amountPaid": "المبلغ المدفوع",
    "transactions.table.amountDue": "المبلغ المتبقي",
    "transactions.table.status": "الحالة",
    "transactions.table.date": "التاريخ",
    "transactions.table.actions": "الإجراءات",
    "transactions.table.items.count": "عناصر",
    "transactions.status.completed": "مكتمل",
    "transactions.status.pending": "معلق",
    "transactions.status.due": "متبقي",
    "transactions.status.cancelled": "ملغي",
    "transactions.actions.view": "عرض",
    "transactions.actions.print": "طباعة",
    "transactions.actions.update": "تحديث",
    "transactions.actions.update.success": "تم تحديث المعاملة بنجاح!",
    "transactions.actions.print.success": "تم طباعة الإيصال بنجاح!",
    "transactions.empty.title": "لم يتم العثور على معاملات",
    "transactions.empty.subtitle":
      "ستظهر المعاملات هنا عندما يقوم العملاء بالشراء",
    "transactions.detail.title": "تفاصيل المعاملة",
    "transactions.detail.transaction.id": "رقم المعاملة",
    "transactions.detail.status": "الحالة",
    "transactions.detail.customer": "العميل",
    "transactions.detail.date": "التاريخ",
    "transactions.detail.items": "العناصر",
    "transactions.detail.total": "المجموع",
    "transactions.detail.payment.method": "طريقة الدفع",
    "transactions.detail.close": "إغلاق",
    "transactions.loading": "جاري تحميل المعاملات...",

    // Dashboard
    "dashboard.title": "لوحة التحكم",
    "dashboard.stats.today.sales": "مبيعات اليوم",
    "dashboard.stats.active.employees": "الموظفين النشطين",
    "dashboard.stats.low.stock": "مخزون منخفض",
    "dashboard.stats.orders.today": "طلبات اليوم",
    "dashboard.recent.sales": "المبيعات الأخيرة",
    "dashboard.alerts.notifications": "التنبيهات والإشعارات",
    "dashboard.current.shift": "الوردية الحالية",
    "dashboard.quick.actions": "إجراءات سريعة",
    "dashboard.new.sale": "بيع جديد",
    "dashboard.add.inventory": "إضافة مخزون",
    "dashboard.schedule.staff": "جدولة الموظفين",
    "dashboard.view.reports": "عرض التقارير",
    "dashboard.on.duty": "في الخدمة",
    "dashboard.starts.at": "يبدأ في",
    "dashboard.view.all.notifications": "عرض جميع الإشعارات",
    "dashboard.items": "عناصر",
    "loading.dashboard": "جاري تحميل لوحة التحكم...",
    "dashboard.unknown.cashier": "أمين صندوق غير معروف",
    "dashboard.walkin.customer": "عميل مباشر",
    "dashboard.low.stock.alert":
      "المخزن منخفض للمنتج {name} (المتبقي {stock} وحدة)",

    // Users
    "users.title": "المستخدمين",
    "users.add.user": "إضافة مستخدم",
    "users.add.title": "إضافة مستخدم جديد",
    "users.edit.title": "تعديل المستخدم",
    "users.view.title": "عرض المستخدم",
    "users.delete.confirm": "هل أنت متأكد من حذف هذا المستخدم؟",
    "users.search.placeholder": "البحث عن المستخدمين...",
    "users.filter.all.roles": "جميع الأدوار",
    "users.filter.all.status": "جميع الحالات",
    "users.status.active": "نشط",
    "users.status.inactive": "غير نشط",
    "users.stats.total": "إجمالي المستخدمين",
    "users.stats.active": "المستخدمين النشطين",
    "users.stats.admins": "المديرين",
    "users.stats.managers": "مديري الأقسام",
    "users.table.user": "المستخدم",
    "users.table.contact": "الاتصال",
    "users.table.role": "الدور",
    "users.table.status": "الحالة",
    "users.table.last.login": "آخر دخول",
    "users.table.actions": "الإجراءات",
    "users.actions.edit": "تعديل",
    "users.actions.delete": "حذف",
    "users.actions.view": "عرض",
    "users.empty.title": "لم يتم العثور على مستخدمين",
    "users.empty.subtitle": "أضف مستخدمين للبدء",
    "users.form.name": "الاسم الكامل",
    "users.form.email": "البريد الإلكتروني",
    "users.form.phone": "الهاتف",
    "users.form.employee.id": "رقم الموظف",
    "users.form.password": "كلمة المرور",
    "users.form.role": "الدور",
    "users.form.status": "الحالة",
    "users.form.name.placeholder": "أدخل الاسم الكامل",
    "users.form.email.placeholder": "أدخل البريد الإلكتروني",
    "users.form.phone.placeholder": "أدخل رقم الهاتف",
    "users.form.employee.id.placeholder": "أدخل رقم الموظف",
    "users.form.password.placeholder": "أدخل كلمة المرور",
    "users.form.cancel": "إلغاء",
    "users.form.add": "إضافة مستخدم",
    "users.form.save": "حفظ التغييرات",
    "users.form.adding": "جاري الإضافة...",
    "users.form.saving": "جاري الحفظ...",
    "users.info.last.login": "آخر دخول",
    "users.info.created": "تم الإنشاء",
    "users.info.updated": "تم التحديث",
    "users.access.denied.title": "تم رفض الوصول",
    "users.access.denied.message": "ليس لديك صلاحية للوصول إلى هذه الصفحة",

    // Categories
    "categories.title": "الفئات",
    "categories.add.category": "إضافة فئة",
    "categories.add.title": "إضافة فئة جديدة",
    "categories.edit.title": "تعديل الفئة",
    "categories.view.title": "عرض الفئة",
    "categories.delete.confirm": "هل أنت متأكد من حذف هذه الفئة؟",
    "categories.search.placeholder": "البحث في الفئات...",
    "categories.stats.total": "إجمالي الفئات",
    "categories.stats.products": "إجمالي المنتجات",
    "categories.stats.average": "متوسط لكل فئة",
    "categories.products": "منتجات",
    "categories.updated": "محدث",
    "categories.empty.title": "لم يتم العثور على فئات",
    "categories.empty.subtitle": "أضف فئات لتنظيم منتجاتك",
    "categories.form.name": "اسم الفئة",
    "categories.form.description": "الوصف",
    "categories.form.color": "اللون",
    "categories.form.image": "صورة الفئة",
    "categories.form.name.placeholder": "أدخل اسم الفئة",
    "categories.form.description.placeholder": "أدخل وصف الفئة",
    "categories.form.image.choose": "اختر صورة",
    "categories.form.image.remove": "إزالة الصورة",
    "categories.form.image.help": "حد أقصى 5 ميجابايت، JPG/PNG/GIF",
    "categories.form.cancel": "إلغاء",
    "categories.form.add": "إضافة فئة",
    "categories.form.save": "حفظ التغييرات",
    "categories.form.adding": "جاري الإضافة...",
    "categories.form.saving": "جاري الحفظ...",
    "categories.actions.edit": "تعديل",
    "categories.actions.delete": "حذف",
    "categories.actions.view": "عرض",
    "categories.info.products": "المنتجات",
    "categories.info.created": "تم الإنشاء",
    "categories.info.updated": "تم التحديث",

    // Suppliers
    "suppliers.title": "الموردين",
    "suppliers.add.supplier": "إضافة مورد",
    "suppliers.add.title": "إضافة مورد جديد",
    "suppliers.edit.title": "تعديل المورد",
    "suppliers.view.title": "عرض المورد",
    "suppliers.delete.confirm": "هل أنت متأكد من حذف هذا المورد؟",
    "suppliers.search.placeholder": "البحث عن الموردين...",
    "suppliers.filter.all.status": "جميع الحالات",
    "suppliers.status.active": "نشط",
    "suppliers.status.inactive": "غير نشط",
    "suppliers.stats.total": "إجمالي الموردين",
    "suppliers.stats.active": "الموردين النشطين",
    "suppliers.stats.products": "إجمالي المنتجات",
    "suppliers.stats.average": "متوسط لكل مورد",
    "suppliers.table.supplier": "المورد",
    "suppliers.table.contact": "الاتصال",
    "suppliers.table.location": "الموقع",
    "suppliers.table.products": "المنتجات",
    "suppliers.table.status": "الحالة",
    "suppliers.table.actions": "الإجراءات",
    "suppliers.products.supplied": "منتجات موردة",
    "suppliers.actions.edit": "تعديل",
    "suppliers.actions.delete": "حذف",
    "suppliers.actions.view": "عرض",
    "suppliers.empty.title": "لم يتم العثور على موردين",
    "suppliers.empty.subtitle": "أضف موردين لإدارة مخزونك",
    "suppliers.form.name": "اسم المورد",
    "suppliers.form.contact.person": "شخص الاتصال",
    "suppliers.form.email": "البريد الإلكتروني",
    "suppliers.form.phone": "الهاتف",
    "suppliers.form.address": "عنوان الشارع",
    "suppliers.form.city": "المدينة",
    "suppliers.form.state": "الولاية",
    "suppliers.form.zip.code": "الرمز البريدي",
    "suppliers.form.country": "البلد",
    "suppliers.form.payment.terms": "شروط الدفع",
    "suppliers.form.status": "الحالة",
    "suppliers.form.name.placeholder": "أدخل اسم المورد",
    "suppliers.form.contact.person.placeholder": "أدخل شخص الاتصال",
    "suppliers.form.email.placeholder": "أدخل البريد الإلكتروني",
    "suppliers.form.phone.placeholder": "أدخل رقم الهاتف",
    "suppliers.form.address.placeholder": "أدخل عنوان الشارع",
    "suppliers.form.city.placeholder": "أدخل المدينة",
    "suppliers.form.state.placeholder": "أدخل الولاية",
    "suppliers.form.zip.code.placeholder": "أدخل الرمز البريدي",
    "suppliers.form.country.placeholder": "أدخل البلد",
    "suppliers.form.cancel": "إلغاء",
    "suppliers.form.add": "إضافة مورد",
    "suppliers.form.save": "حفظ التغييرات",
    "suppliers.form.adding": "جاري الإضافة...",
    "suppliers.form.saving": "جاري الحفظ...",
    "suppliers.info.products.supplied": "المنتجات الموردة",
    "suppliers.info.created": "تم الإنشاء",
    "suppliers.info.updated": "تم التحديث",

    // Inventory
    "inventory.title": "المخزن",
    "inventory.add.item": "إضافة عنصر",
    "inventory.add.title": "إضافة عنصر جديد",
    "inventory.edit.title": "تعديل العنصر",
    "inventory.view.title": "عرض العنصر",
    "inventory.delete.confirm": "هل أنت متأكد من حذف هذا العنصر؟",
    "inventory.search.placeholder": "البحث في المخزن...",
    "inventory.filter.all.categories": "جميع الفئات",
    "inventory.filter.all.stock": "جميع المخزن",
    "inventory.filter.in.stock": "متوفر",
    "inventory.filter.low.stock": "مخزون منخفض",
    "inventory.filter.out.of.stock": "نفد المخزن",
    "inventory.stats.total.items": "إجمالي العناصر",
    "inventory.stats.low.stock": "مخزون منخفض",
    "inventory.stats.out.of.stock": "نفد المخزن",
    "inventory.stats.total.value": "القيمة الإجمالية",
    "inventory.table.product": "المنتج",
    "inventory.table.sku": "SKU",
    "inventory.table.category": "الفئة",
    "inventory.table.stock": "المخزن",
    "inventory.table.price": "السعر",
    "inventory.table.supplier": "المورد",
    "inventory.table.actions": "الإجراءات",
    "inventory.last.restocked": "آخر تجديد",
    "inventory.actions.edit": "تعديل",
    "inventory.actions.delete": "حذف",
    "inventory.actions.view": "عرض",
    "inventory.empty.title": "لم يتم العثور على عناصر مخزون",
    "inventory.empty.subtitle": "أضف عناصر لإدارة مخزونك",
    "inventory.form.name": "اسم المنتج",
    "inventory.form.sku": "SKU",
    "inventory.form.category": "الفئة",
    "inventory.form.supplier": "المورد",
    "inventory.form.cost.price": "سعر التكلفة",
    "inventory.form.selling.price": "سعر البيع",
    "inventory.form.stock": "كمية المخزن",
    "inventory.form.reorder.level": "مستوى إعادة الطلب",
    "inventory.form.description": "الوصف",
    "inventory.form.image": "صورة المنتج",
    "inventory.form.name.placeholder": "أدخل اسم المنتج",
    "inventory.form.sku.placeholder": "أدخل SKU",
    "inventory.form.description.placeholder": "أدخل وصف المنتج",
    "inventory.form.select.category": "اختر الفئة",
    "inventory.form.select.supplier": "اختر المورد",
    "inventory.form.image.choose": "اختر صورة",
    "inventory.form.image.remove": "إزالة الصورة",
    "inventory.form.image.help": "حد أقصى 5 ميجابايت، JPG/PNG/GIF",
    "inventory.form.cancel": "إلغاء",
    "inventory.form.add": "إضافة عنصر",
    "inventory.form.save": "حفظ التغييرات",
    "inventory.form.adding": "جاري الإضافة...",
    "inventory.form.saving": "جاري الحفظ...",
    "inventory.info.supplier": "المورد",
    "inventory.info.last.restocked": "آخر تجديد",
    "inventory.info.created": "تم الإنشاء",

    // Profile
    "profile.title": "الملف الشخصي",
    "profile.edit": "تعديل الملف الشخصي",
    "profile.save": "حفظ التغييرات",
    "profile.cancel": "إلغاء",
    "profile.saving": "جاري الحفظ...",
    "profile.personal.info": "المعلومات الشخصية",
    "profile.work.info": "معلومات العمل",
    "profile.performance": "إحصائيات الأداء",
    "profile.full.name": "الاسم الكامل",
    "profile.employee.id": "رقم الموظف",
    "profile.email": "البريد الإلكتروني",
    "profile.phone": "الهاتف",
    "profile.address": "العنوان",
    "profile.role": "الدور",
    "profile.department": "القسم",
    "profile.join.date": "تاريخ الانضمام",
    "profile.phone.placeholder": "أدخل رقم الهاتف",
    "profile.address.placeholder": "أدخل العنوان",
    "profile.phone.not.set": "غير محدد",
    "profile.name.readonly": "اتصل بالمدير لتغيير الاسم",
    "profile.email.readonly": "اتصل بالمدير لتغيير البريد الإلكتروني",
    "profile.change.password": "تغيير كلمة المرور",
    "profile.current.password": "كلمة المرور الحالية",
    "profile.new.password": "كلمة المرور الجديدة",
    "profile.confirm.password": "تأكيد كلمة المرور",
    "profile.current.password.placeholder": "أدخل كلمة المرور الحالية",
    "profile.new.password.placeholder": "أدخل كلمة المرور الجديدة",
    "profile.confirm.password.placeholder": "أكد كلمة المرور الجديدة",
    "profile.password.requirements": "كلمة المرور يجب أن تكون 6 أحرف على الأقل",
    "profile.change.password.button": "تغيير كلمة المرور",
    "profile.changing.password": "جاري التغيير...",
    "profile.update.success": "تم تحديث الملف الشخصي بنجاح",
    "profile.password.change.success": "تم تغيير كلمة المرور بنجاح",
    "profile.stats.total.sales": "إجمالي المبيعات",
    "profile.stats.transactions": "المعاملات",
    "profile.stats.days.active": "أيام النشاط",
    "profile.stats.last.login": "آخر دخول",

    // Reports
    "reports.title": "التقارير",
    "reports.overview": "نظرة عامة",
    "reports.sales": "المبيعات",
    "reports.inventory": "المخزن",
    "reports.customers": "العملاء",
    "reports.products": "المنتجات",
    "reports.date.today": "اليوم",
    "reports.date.yesterday": "أمس",
    "reports.date.week": "آخر 7 أيام",
    "reports.date.month": "آخر 30 يوم",
    "reports.date.quarter": "آخر 3 أشهر",
    "reports.date.year": "السنة الماضية",
    "reports.date.custom": "نطاق مخصص",
    "reports.export.print": "طباعة",
    "reports.export.pdf": "PDF",
    "reports.export.excel": "Excel",
    "reports.export.csv": "CSV",
    "reports.export.success": "تم تصدير التقرير بنجاح!",
    "reports.metrics.total.sales": "إجمالي المبيعات",
    "reports.metrics.transactions": "المعاملات",
    "reports.metrics.customers": "العملاء",
    "reports.metrics.avg.transaction": "متوسط المعاملة",
    "reports.chart.daily.sales": "المبيعات اليومية",
    "reports.chart.top.products": "أفضل المنتجات",
    "reports.chart.category.sales": "مبيعات الفئات",
    "reports.product.sold": "مباع",
    "reports.table.date": "التاريخ",
    "reports.table.sales": "المبيعات",
    "reports.table.transactions": "المعاملات",
    "reports.table.customers": "العملاء",
    "reports.table.avg.transaction": "متوسط المعاملة",
    "reports.inventory.total.items": "إجمالي العناصر",
    "reports.inventory.low.stock": "مخزون منخفض",
    "reports.inventory.out.of.stock": "نفد المخزن",

    // Settings
    "settings.title": "الإعدادات",
    "settings.tabs.store": "المتجر",
    "settings.tabs.system": "النظام",
    "settings.tabs.receipt": "الإيصال",
    "settings.tabs.notifications": "الإشعارات",
    "settings.tabs.security": "الأمان",
    "settings.tabs.display": "العرض",
    "settings.store.info": "معلومات المتجر",
    "settings.store.name": "اسم المتجر",
    "settings.store.address": "عنوان المتجر",
    "settings.store.phone": "هاتف المتجر",
    "settings.store.email": "بريد المتجر الإلكتروني",
    "settings.tax.settings": "إعدادات الضريبة",
    "settings.tax.rate": "معدل الضريبة",
    "settings.tax.included": "الضريبة مشمولة في الأسعار",
    "settings.system.general": "الإعدادات العامة",
    "settings.system.currency": "العملة",
    "settings.system.date.format": "تنسيق التاريخ",
    "settings.system.time.format": "تنسيق الوقت",
    "settings.system.time.12": "12 ساعة",
    "settings.system.time.24": "24 ساعة",
    "settings.system.low.stock.threshold": "حد المخزن المنخفض",
    "settings.receipt.customization": "تخصيص الإيصال",
    "settings.receipt.header": "رأس الإيصال",
    "settings.receipt.footer": "تذييل الإيصال",
    "settings.receipt.printing": "خيارات الطباعة",
    "settings.receipt.print.logo": "طباعة الشعار على الإيصال",
    "settings.receipt.auto.print": "طباعة تلقائية للإيصالات",
    "settings.notifications.alerts": "إعدادات التنبيه",
    "settings.notifications.low.stock": "تنبيهات المخزن المنخفض",
    "settings.notifications.email": "إشعارات البريد الإلكتروني",
    "settings.notifications.sound": "المؤثرات الصوتية",
    "settings.security.access": "التحكم في الوصول",
    "settings.security.session.timeout": "انتهاء مهلة الجلسة",
    "settings.security.minutes": "دقائق",
    "settings.security.password.change": "طلب تغيير كلمة المرور بانتظام",
    "settings.security.two.factor": "المصادقة الثنائية",
    "settings.display.appearance": "المظهر",
    "settings.display.theme": "السمة",
    "settings.display.theme.light": "فاتح",
    "settings.display.theme.dark": "داكن",
    "settings.display.theme.auto": "تلقائي",
    "settings.display.compact.mode": "الوضع المضغوط",
    "settings.display.product.images": "عرض صور المنتجات",
    "settings.save.changes": "حفظ التغييرات",
    "settings.reset.defaults": "إعادة تعيين للافتراضي",
    "settings.reset.confirm":
      "هل أنت متأكد من إعادة تعيين جميع الإعدادات للافتراضي؟",
    "settings.saved.successfully": "تم حفظ الإعدادات بنجاح",
    "settings.unsaved.changes": "لديك تغييرات غير محفوظة",
  },
};

export const LanguageProvider: React.FC<LanguageProviderProps> = ({
  children,
}) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("pos-language");
    return saved === "en" || saved === "ar" ? saved : "ar";
  });

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem("pos-language") as Language;
    if (savedLanguage && (savedLanguage === "en" || savedLanguage === "ar")) {
      setLanguageState(savedLanguage);
    }
  }, []);

  // Apply language settings to document
  useEffect(() => {
    const root = document.documentElement;

    // Set direction
    root.dir = language === "ar" ? "rtl" : "ltr";

    // Set language attribute
    root.lang = language;

    // Save to localStorage
    localStorage.setItem("pos-language", language);
  }, [language]);

  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
